using System;
using System.Collections.Generic;
using System.Threading;
using UnityEngine;

public static class AwaitablesExtensions
{

    // generated by Google AI
    public static async Awaitable WhenAll(IReadOnlyList<Awaitable> awaitables)
    {
        var count = awaitables.Count;
        if (count == 0) return;

        var completion = new AwaitableCompletionSource();
        var remaining = count;
        List<Exception> exceptions = null;

        foreach (var awaitable in awaitables)
        {
            TrackAwaitable(awaitable);
        }

        await completion.Awaitable;

        if (exceptions != null)
        {
            throw new AggregateException(exceptions);
        }

        async void TrackAwaitable(Awaitable awaitable)
        {
            try
            {
                await awaitable;
            }
            catch (Exception ex)
            {
                LazyInitializer.EnsureInitialized(ref exceptions, () => new List<Exception>());
                lock (exceptions)
                {
                    exceptions.Add(ex);
                }
            }
            finally
            {
                if (Interlocked.Decrement(ref remaining) == 0)
                {
                    completion.SetResult();
                }
            }
        }
    }


    // generated by Google AI
    public static async Awaitable<IReadOnlyList<T>> WhenAll<T>(IReadOnlyList<Awaitable<T>> awaitables)
    {
        var count = awaitables.Count;
        var resultsList = new T[count];
        if (count == 0) return resultsList;

        var completion = new AwaitableCompletionSource();
        var remaining = count;
        List<Exception> exceptions = null;

        for (var i = 0; i < count; i++)
        {
            var index = i;
            TrackAwaitable(awaitables[index], index);
        }

        await completion.Awaitable;

        if (exceptions != null)
        {
            throw new AggregateException(exceptions);
        }

        return resultsList;

        async void TrackAwaitable(Awaitable<T> awaitable, int index)
        {
            try
            {
                var result = await awaitable;
                resultsList[index] = result;
            }
            catch (Exception ex)
            {
                LazyInitializer.EnsureInitialized(ref exceptions, () => new List<Exception>());
                lock (exceptions)
                {
                    exceptions.Add(ex);
                }
            }
            finally
            {
                if (Interlocked.Decrement(ref remaining) == 0)
                {
                    completion.SetResult();
                }
            }
        }
    }

    public static Awaitable<T> FromResult<T>(T result)
    {
        var completionSource = new AwaitableCompletionSource<T>();
        completionSource.SetResult(result);

        return completionSource.Awaitable;
    }

}

