using Unity.Burst;
using UnityEngine;
using Unity.Mathematics;
using System.Runtime.CompilerServices;

public static class MathExtensions
{
    [BurstCompile]
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static float3 LocalToWorldPos(RigidTransform point, float3 localPosition) => point.pos + math.mul(point.rot, localPosition);

    // generated by Google AI
    [BurstCompile]
    public static quaternion RotateTowards(quaternion from, quaternion to, float maxAngleDelta)
    {
        float dot = math.clamp(math.dot(from, to), -1f, 1f);
        float angle = math.acos(math.abs(dot)) * 2f;
        if (angle <= maxAngleDelta || angle < math.EPSILON)
        {
            return to;
        }
        float t = maxAngleDelta / angle;
        quaternion target = dot < 0f ? new quaternion(-to.value) : to;

        return math.slerp(from, target, t);
    }

    // generated by Google AI
    [BurstCompile]
    public static float3 InverseTransformPoint(float3 globalPos, float3 objectGlobalPos, quaternion objectGlobalRot)
    {
        float3 offset = globalPos - objectGlobalPos;
        quaternion inverseRot = math.conjugate(objectGlobalRot);
        float3 localPoint = math.mul(inverseRot, offset);

        return localPoint;
    }

    // generated by Deepseek, corrected 1 by GoogleAI, corrected 2 by Deepseek, checked by GoogleAI
    [BurstCompile]
    public static quaternion FromToRotation(float3 from, float3 to)
    {
        float d = math.dot(from, to);

        if (d > 0.9999f)
            return quaternion.identity;

        if (d < -0.9999f)
        {
            float3 axis = math.cross(from, new float3(0f, 0f, 1f));
            if (math.lengthsq(axis) < 0.0001f)
            {
                axis = math.cross(from, new float3(0f, 1f, 0f));
            }

            return quaternion.AxisAngle(math.normalize(axis), math.PI);
        }

        float3 cross = math.cross(from, to);
        quaternion q = new quaternion(cross.x, cross.y, cross.z, 1f + d);

        return math.normalize(q);
    }

    [BurstCompile]
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static float3 ProjectOnPlane(this float3 vector, float3 planeNormal)
    {
        var dot = math.dot(vector, planeNormal);
        return vector - dot * planeNormal;
    }

    [BurstCompile]
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static RigidTransform ToRigidTransform(this Transform transform) => new(transform.rotation, transform.position);

    [BurstCompile]
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static float3 GetRightVector(in RigidTransform transform) => math.mul(transform.rot, math.right());

    [BurstCompile]
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static quaternion RotateTowards(in quaternion from, in quaternion to, float angleInDegrees)
    {
        var maxAngle = math.angle(from, to) * math.TODEGREES;
        if (maxAngle == 0f)
        {
            return to;
        }

        return math.slerp(from, to, math.min(1f, angleInDegrees / maxAngle));
    }

    [BurstCompile]
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static float3 MoveTowards(float3 current, float3 target, float maxDelta)
    {
        var dir = target - current;
        var sqlen = math.lengthsq(dir);
        if (sqlen <= maxDelta * maxDelta)
        {
            return target;
        }
        var rlen = math.rsqrt(sqlen);
        return current + dir * rlen * maxDelta;
    }

    [BurstCompile]
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    // generated by Google AI
    public static float MoveTowards(float current, float target, float maxDelta)
    {
        float absMaxDelta = math.abs(maxDelta);
        float clampedDelta = math.clamp(target - current, -absMaxDelta, absMaxDelta);

        return current + clampedDelta;
    }

    // generated by Deepseek, checked by Google AI
    [BurstCompile]
    public static float GetSignedAngleInPlane(float3 from, float3 to, float3 planeNormal)
    {
        float dot = math.dot(from, to);
        float det = math.dot(math.cross(from, to), planeNormal);

        return math.atan2(det, dot); 
    }
}
