using Unity.Burst;
using UnityEngine;
using Unity.Mathematics;
using System.Runtime.CompilerServices;

public static class MathExtensions
{
    [BurstCompile]
    public static quaternion GetLimitedNormalizedRotation(float2 normalizedRotationLerpValue, float2 limits)
    {
        normalizedRotationLerpValue = math.clamp(normalizedRotationLerpValue, 0f, 1f);
        limits = math.clamp(limits, -1f, 1f);

        // dot with forward is Y coord
        var maxAngleRadianX = math.acos(limits.x);
        var angleRadianX = math.lerp(- maxAngleRadianX, maxAngleRadianX, normalizedRotationLerpValue.x);

        var maxAngleRadianY = math.acos(limits.y);
        var angleRadianY = math.lerp(-maxAngleRadianY, maxAngleRadianY, normalizedRotationLerpValue.y);

       // UnityEngine.Debug.Log($"X: {limits.x} : {math.degrees( - maxAngleRadianX)} -> {math.degrees(maxAngleRadianX)} = {angleRadianX} / {math.degrees(angleRadianX)}");
       // UnityEngine.Debug.Log($"Y: {limits.y} : {math.degrees( - maxAngleRadianY)} -> {math.degrees(maxAngleRadianY)} = {angleRadianY} / {math.degrees(angleRadianY)}");

        Quaternion rotY = Quaternion.AngleAxis(math.degrees(angleRadianY), Vector3.up);
        Quaternion rotX = Quaternion.AngleAxis(math.degrees(angleRadianX), Vector3.right);
        return math.mul(rotY, rotX);
    }


    // generated by Google AI
    [BurstCompile]
    public static quaternion ClampRotation(quaternion q, float2 limits)
    {
        // 1. Извлекаем чистый вектор направления взгляда. 
        float3 forward = math.forward(q);

        // 2. Ограничение PITCH (Вверх / Вниз)
        // limits.x — это косинус максимального угла отклонения от горизонтали (плоскости XZ)
        if (limits.x > -1f)
        {
            // Проекция на вертикальную ось Y не должна превышать синус предельного угла
            // Синус находим через косинус: sin = sqrt(1 - cos^2)
            float maxSinPitch = math.sqrt(1f - limits.x * limits.x);

            // Если текущий Y (синус угла) больше допустимого, зажимаем его
            if (math.abs(forward.y) > maxSinPitch)
            {
                forward.y = math.select(-maxSinPitch, maxSinPitch, forward.y > 0f);

                // Корректируем длину XZ, чтобы общая длина вектора осталась равной 1
                float scaleXZ = math.sqrt(1f - forward.y * forward.y) / (math.length(forward.xz) + 1e-6f);
                forward.x *= scaleXZ;
                forward.z *= scaleXZ;
            }
        }

        // 3. Ограничение YAW (Влево / Вправо)
        // limits.y — это косинус максимального угла отклонения от центральной оси Z
        if (limits.y > -1f)
        {
            // Нормализуем проекцию на плоскость XZ, чтобы проверить чистый поворот влево/вправо
            float lenXZ = math.length(forward.xz);
            if (lenXZ > 1e-6f)
            {
                float3 normXZ = new float3(forward.x, 0f, forward.z) / lenXZ;

                // Вектор normXZ.z — это и есть косинус угла Yaw. Он не должен быть меньше лимита.
                if (normXZ.z < limits.y)
                {
                    // Зажимаем косинус на границе лимита
                    normXZ.z = limits.y;
                    // Рассчитываем новый X (синус) с сохранением исходного знака поворота
                    normXZ.x = math.select(-1f, 1f, forward.x >= 0f) * math.sqrt(1f - limits.y * limits.y);

                    // Возвращаем скорректированную проекцию обратно в forward
                    forward.x = normXZ.x * lenXZ;
                    forward.z = normXZ.z * lenXZ;
                }
            }
        }

        // 4. Собираем кватернион через LookRotation.
        // math.normalize гарантирует, что на входе будет идеальный единичный вектор.
        return quaternion.LookRotation(math.normalize(forward), new float3(0f, 1f, 0f));
    }

    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    [BurstCompile]
    public static float2 GetAxisProjectionsFast2D(quaternion q)
    {
        float4 v = q.value;

        return new float2(
            v.w * v.w + v.x * v.x - v.y * v.y - v.z * v.z,  // rawDots.x: Локальный Right · Мировой Right
            v.w * v.w - v.x * v.x + v.y * v.y - v.z * v.z   // rawDots.y: Локальный Up · Мировой Up
        );
    }

    [BurstCompile]
    public static bool IsQuaternionNormalized(quaternion rot) => math.abs(math.lengthsq(rot) - 1.0f) < 0.0001f;

    [BurstCompile]
    public static RigidTransform Lerp(RigidTransform pointA, RigidTransform pointB, float t)
    {
        t = math.clamp(t, 0f, 1f);
        var pos = math.lerp(pointA.pos, pointB.pos, t);
        var rot = math.slerp(pointA.rot, pointB.rot, t);
        return new(rot, pos);
    }

    [BurstCompile]
    public static int UnitsRadiusToTriangular(float radiusInUnits, float triangleHeight) => (int)math.round(radiusInUnits / triangleHeight) + 1;

    [BurstCompile]    
    public static void ComputeAABB(float2 size, float3 position, quaternion rotation, out float3 min, out float3 max)
    {
        // generated by Google AI
        float2 halfSize = size * 0.5f;

        float3 dirX = math.mul(rotation, new float3(1, 0, 0)) * halfSize.x;
        float3 dirZ = math.mul(rotation, new float3(0, 0, 1)) * halfSize.y;
        float3 extents = math.abs(dirX) + math.abs(dirZ);

        min = position - extents;
        max = position + extents;
    }

    [BurstDiscard]
    public static RigidTransform CalculateLocalPointInPointSpace(Transform spaceTransform, Transform calculatingTransform)
    {
        // generated by Deepseek

        float4x4 chassisLocalMatrix = math.mul(
           spaceTransform.worldToLocalMatrix,
           calculatingTransform.localToWorldMatrix
       );

        float3 localPosition = chassisLocalMatrix.c3.xyz;

        quaternion localRotation = quaternion.LookRotation(
            chassisLocalMatrix.c2.xyz,
            chassisLocalMatrix.c1.xyz
        );

        return new(localRotation, localPosition);
    }


    [BurstCompile]
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static float3 LocalToWorldPos(RigidTransform point, float3 localPosition) => point.pos + math.mul(point.rot, localPosition);

    // generated by Google AI
    [BurstCompile]
    public static quaternion RotateTowards(quaternion from, quaternion to, float maxAngleDelta)
    {
        float dot = math.clamp(math.dot(from, to), -1f, 1f);
        float angle = math.acos(math.abs(dot)) * 2f;
        if (angle <= maxAngleDelta || angle < math.EPSILON)
        {
            return to;
        }
        float t = maxAngleDelta / angle;
        quaternion target = dot < 0f ? new quaternion(-to.value) : to;

        return math.slerp(from, target, t);
    }

    [BurstCompile]
    public static float3 InverseTransformPoint(float3 globalPos, RigidTransform rigidTransform) =>
        InverseTransformPoint(globalPos, rigidTransform.pos, rigidTransform.rot);

    // generated by Google AI
    [BurstCompile]
    public static float3 InverseTransformPoint(float3 globalPos, float3 objectGlobalPos, quaternion objectGlobalRot)
    {
        float3 offset = globalPos - objectGlobalPos;
        quaternion inverseRot = math.conjugate(objectGlobalRot);
        float3 localPoint = math.mul(inverseRot, offset);

        return localPoint;
    }

    // generated by Deepseek, corrected 1 by GoogleAI, corrected 2 by Deepseek, checked by GoogleAI
    [BurstCompile]
    public static quaternion FromToRotation(float3 from, float3 to)
    {
        float d = math.dot(from, to);

        if (d > 0.9999f)
            return quaternion.identity;

        if (d < -0.9999f)
        {
            float3 axis = math.cross(from, new float3(0f, 0f, 1f));
            if (math.lengthsq(axis) < 0.0001f)
            {
                axis = math.cross(from, new float3(0f, 1f, 0f));
            }

            return quaternion.AxisAngle(math.normalize(axis), math.PI);
        }

        float3 cross = math.cross(from, to);
        quaternion q = new quaternion(cross.x, cross.y, cross.z, 1f + d);

        return math.normalize(q);
    }

    [BurstCompile]
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static float3 ProjectOnPlane(this float3 vector, float3 planeNormal)
    {
        var dot = math.dot(vector, planeNormal);
        return vector - dot * planeNormal;
    }

    [BurstCompile]
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    // generated by Deepseek
    public static float3 ProjectPointOnPlane(float3 point, float4 plane)
    {
        float distance = math.dot(plane.xyz, point) + plane.w;
        return point - distance * plane.xyz;
    }

    [BurstCompile]
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static RigidTransform ToRigidTransform(this Transform transform) => new(transform.rotation, transform.position);

    [BurstCompile]
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static float3 GetRightVector(in RigidTransform transform) => math.mul(transform.rot, math.right());

    [BurstCompile]
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static quaternion RotateTowards(in quaternion from, in quaternion to, float angleInDegrees)
    {
        var maxAngle = math.angle(from, to) * math.TODEGREES;
        if (maxAngle == 0f)
        {
            return to;
        }

        return math.slerp(from, to, math.min(1f, angleInDegrees / maxAngle));
    }

    [BurstCompile]
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static float3 MoveTowards(float3 current, float3 target, float maxDelta)
    {
        var dir = target - current;
        var sqlen = math.lengthsq(dir);
        if (sqlen <= maxDelta * maxDelta)
        {
            return target;
        }
        var rlen = math.rsqrt(sqlen);
        return current + dir * rlen * maxDelta;
    }

    [BurstCompile]
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    // generated by Google AI
    public static float MoveTowards(float current, float target, float maxDelta)
    {
        float absMaxDelta = math.abs(maxDelta);
        float clampedDelta = math.clamp(target - current, -absMaxDelta, absMaxDelta);

        return current + clampedDelta;
    }

    // generated by Deepseek, checked by Google AI
    [BurstCompile]
    public static float GetSignedAngleInPlane(float3 from, float3 to, float3 planeNormal)
    {
        float dot = math.dot(from, to);
        float det = math.dot(math.cross(from, to), planeNormal);

        return math.atan2(det, dot); 
    }
}
