using System.Text.RegularExpressions;

namespace ZE.Utils
{
    public static class StringExtension
    {
        // alternative option:  JsonNamingPolicy.SnakeCaseLower.ConvertName(input); (require json package)
        // generated by Google AI
        public static string ToSnakeCase(this string input) =>
                    string.IsNullOrEmpty(input)
                        ? input
                        : Regex.Replace(input, "(?<!^)([A-Z])", "_$1").ToLower();

        public static string ToSnakeCaseWithAcronyms(string input)
        {
            if (string.IsNullOrEmpty(input)) return input;

            // 1. Разделяем стык между строчной и заглавной (например: 'eW' -> 'e_W')
            string result = Regex.Replace(input, @"([a-z0-9])([A-Z])", "$1_$2");

            // 2. Разделяем стык между аббревиатурой и следующим словом (например: 'UIW' -> 'UI_W')
            result = Regex.Replace(result, @"([A-Z]+)([A-Z][a-z])", "$1_$2");

            // 3. Переводим всё в нижний регистр
            return result.ToLower();
        }
    }
}
