using System;
using VContainer;
public interface IResourceBinder
{
    public void Register(IContainerBuilder builder);
}

// generated by Chat GPT

public class ResourceBinding<TImplementation, TInterface> : IResourceBinder
    where TImplementation : class, TInterface
{
    private readonly TImplementation _instance;

    public ResourceBinding(TImplementation instance)
    {
        _instance = instance ?? throw new ArgumentNullException(nameof(instance));
    }

    public void Register(IContainerBuilder builder)
    {
        builder.RegisterInstance(_instance)
               .As<TInterface>()
               .AsSelf();
    }
}

// generated by Chat GPT
public class ResourceBinding<TImplementation> : IResourceBinder where TImplementation : class
{
    private readonly TImplementation _instance;

    public ResourceBinding(TImplementation instance)
    {
        _instance = instance ?? throw new ArgumentNullException(nameof(instance));
    }

    public void Register(IContainerBuilder builder)
    {
        builder.RegisterInstance(_instance).AsSelf();
    }
}
