using Unity.Mathematics;
using Unity.Collections;
using Unity.Burst;
using System;
using UnityEngine;
using System.Collections.Generic;

namespace ZE.MechBattle.Navigation
{
    public readonly struct OrientedPoint
    {
        public readonly float3 Position;
        public readonly float3 Normal;

        public OrientedPoint(float3 pos, float3 normal)
        {
            Position = pos;
            Normal = normal;
        }
    }

    public static class CalculateRansacPlaneCommand
    {
        private static uint _seed = 1;

        // generated by Google AI
        //todo: make more unified (this time is job-specific: operated only a part of array by startIndex)
        [BurstCompile]
        public static void Execute(
            NativeArray<RaycastHit> hits, 
            int startIndex, 
            Span<float> heights, 
            int raycastsPerTriangle,
            int ransacIterationsCount,
            float ransacThreshold)
        {
            float4 bestPlane = new float4(0, 1, 0, -heights[0]);
            int maxInliers = -1;
            var rng = new Unity.Mathematics.Random((uint)startIndex + 1);

            for (int i = 0; i < ransacIterationsCount; i++)
            {
                int idx = rng.NextInt(0, raycastsPerTriangle);
                var hit = hits[startIndex + idx];
                if (hit.colliderInstanceID == 0) continue;

                float3 p = new float3(hit.point.x, heights[idx], hit.point.z);
                float3 n = hit.normal;

                if (math.abs(n.y) < 0.01f) continue;

                float4 currentPlane = new float4(n, -math.dot(n, p));

                int inliersCount = 0;
                for (int j = 0; j < raycastsPerTriangle; j++)
                {
                    var h = hits[startIndex + j];
                    float3 pCurr = new float3(h.point.x, heights[j], h.point.z);

                    float dist = math.abs(math.dot(currentPlane.xyz, pCurr) + currentPlane.w);
                    float normalDiff = 1f - math.dot(currentPlane.xyz, h.normal);

                    if (dist < ransacThreshold && normalDiff < 0.1f)
                        inliersCount++;
                }

                if (inliersCount > maxInliers)
                {
                    maxInliers = inliersCount;
                    bestPlane = currentPlane;
                }
            }

            if (maxInliers > 0)
            {
                for (int j = 0; j < raycastsPerTriangle; j++)
                {
                    var h = hits[startIndex + j];
                    float3 p = new float3(h.point.x, heights[j], h.point.z);
                    if (math.abs(bestPlane.y) > 0.001f)
                    {
                        heights[j] = -(bestPlane.x * p.x + bestPlane.z * p.z + bestPlane.w) / bestPlane.y;
                    }
                }
            }
        }

        public static bool TryGetBestPlane(
            IReadOnlyList<OrientedPoint> points,
            IList<float> heights,
            int ransacIterationsCount,
            float ransacThreshold,
            out float4 bestPlane)
        {
            // reworked with a help of Deepseek

            bestPlane = new float4(0, 1, 0, -heights[0]);
            int maxInliers = -1;
            var rng = new Unity.Mathematics.Random(GetNextSeed());
            var length = points.Count;

            for (int i = 0; i < ransacIterationsCount; i++)
            {
                int idx = rng.NextInt(0, length);
                var hit = points[idx];

                float3 p = new float3(hit.Position.x, heights[idx], hit.Position.z);
                float3 n = hit.Normal;

                if (math.abs(n.y) < 0.01f) continue;

                float4 currentPlane = new float4(n, -math.dot(n, p));

                int inliersCount = 0;
                for (int j = 0; j < length; j++)
                {
                    var h = points[j];
                    float3 pCurr = new float3(h.Position.x, heights[j], h.Position.z);

                    float dist = math.abs(math.dot(currentPlane.xyz, pCurr) + currentPlane.w);
                    float normalDiff = 1f - math.dot(currentPlane.xyz, h.Normal);

                    if (dist < ransacThreshold && normalDiff < 0.1f)
                        inliersCount++;
                }

                //UnityEngine.Debug.Log($"plane normal: {currentPlane.xyz}, inliers count: {inliersCount} / {length}");

                if (inliersCount > maxInliers)
                {
                    maxInliers = inliersCount;
                    bestPlane = currentPlane;
                }
            }

            return maxInliers > 0;
        }

        private static uint GetNextSeed()
        {
            var seed = _seed;
            _seed += 1121;
            return seed;
        }
    }
}
