using System;
using System.Runtime.Serialization;

namespace ZE.MechBattle
{
    // generated by Deepseek
    [Serializable]
    public class EntityDisposedException : Exception
    {
        public EntityDisposedException() { }
        public EntityDisposedException(string message) : base(message) { }
        public EntityDisposedException(string message, Exception inner) : base(message, inner) { }

        // Для сериализации
        protected EntityDisposedException(SerializationInfo info, StreamingContext context)
            : base(info, context) { }
    }
}
