using Unity.Mathematics;
using UnityEngine;

namespace ZE.MechBattle
{
    [CreateAssetMenu(fileName = "MechChassisData", menuName = "Scriptable Objects/MechChassisData")]
    public class MechChassisData : ScriptableObject
    {
        [field:SerializeField] public RigidTransform ChassisRootLocalPoint { get;private set; }
        [field: SerializeField] public LegDataContainer<RigidTransform> LeftLegLocalPoints { get; private set; }
        [field:SerializeField] public LegDataContainer<RigidTransform> RightLegLocalPoints { get; private set; }
       
        public bool TryUpdateData(MechView mechView)
        {
            if (!CheckViewParts(mechView))
                return false;

           
            ChassisRootLocalPoint = CalculateRootLocalMatrix(mechView);
            LeftLegLocalPoints = WriteLegData(mechView.LeftLeg);
            RightLegLocalPoints = WriteLegData(mechView.RightLeg);
            return true;

            LegDataContainer<RigidTransform> WriteLegData(LegDataContainer<Transform> legData) =>
                new()
                {
                    Hip = GetLocalPoint(legData.Hip),
                    Ankle = GetLocalPoint(legData.Ankle),
                    Foot = GetLocalPoint(legData.Foot),
                };

            RigidTransform GetLocalPoint(Transform transform) => new(transform.localRotation, transform.localPosition);
        }

        // we need local matrix of chassis in root transform space (ignoring parents between them)
        private RigidTransform CalculateRootLocalMatrix(MechView mechView)
        {
            // generated by Deepseek

            float4x4 chassisLocalMatrix = math.mul(
               mechView.transform.worldToLocalMatrix,
               mechView.ChassisRoot.localToWorldMatrix
           );

            float3 localPosition = chassisLocalMatrix.c3.xyz;

            quaternion localRotation = quaternion.LookRotation(
                chassisLocalMatrix.c2.xyz,
                chassisLocalMatrix.c1.xyz 
            );

            return new(localRotation, localPosition);
        }

        private bool CheckViewParts(MechView mechView)
        {
            if (mechView.ChassisRoot == null)
            {
                UnityEngine.Debug.LogError("no chassis root set");
                return false;
            }

            if (!CheckLeg(mechView.LeftLeg, false)) return false;
            if (!CheckLeg(mechView.RightLeg, false)) return false;

            return true;
        }

        private bool CheckLeg(LegDataContainer<Transform> legContainer, bool isRightSide)
        {
            if (legContainer.Hip == null)
            {
                LogAbsenceString("hip");
                return false;
            }

            if (legContainer.Ankle == null)
            {
                LogAbsenceString("ankle");
                return false;
            }

            if (legContainer.Foot == null)
            {
                LogAbsenceString("foot");
                return false;
            }

            return true;

            void LogAbsenceString(string partKey) => UnityEngine.Debug.LogError($"no {(isRightSide ? "right" : "left")} {partKey} set");
        }

    }
}
