using Scellecs.Morpeh;
using VContainer;
using System;

namespace ZE.MechBattle.Ecs
{
    public abstract class FeatureSystemsInstallQueue : IFeatureInstaller
    {
        public const int FACTORY_KEY = 1;

        // generated by ChatGPT
        public interface ISystemsOperator
        {
            void AddSystem<T>(SystemGroupOrder order)
                where T : class, ISystem;

            void AddSystemWithInterface<SystemType, InterfaceType>(SystemGroupOrder order)
                where SystemType : class, ISystem, InterfaceType;
        }

        internal sealed class ContainerSystemsBinder : ISystemsOperator
        {
            private readonly IContainerBuilder builder;

            public ContainerSystemsBinder(IContainerBuilder builder)
            {
                this.builder = builder;
            }

            // IMPROTANT : use only transient to evade double-dispose problems (scope + world dispose)

            public void AddSystem<T>(SystemGroupOrder order)
                where T : class, ISystem
            {
                builder.Register<T>(Lifetime.Transient);
            }

            public void AddSystemWithInterface<SystemType, InterfaceType>(SystemGroupOrder order)
                where SystemType : class, ISystem, InterfaceType
            {
                // also evading double-dispose problem:
                // factory will contain cached system, however it cannot dispose it, world will do it


                // factory-only version
                builder.Register<SystemType>(Lifetime.Scoped).Keyed(FACTORY_KEY);

                // caching factory
                builder.Register<InterfacedSystemFactory<SystemType, InterfaceType>>(Lifetime.Scoped);

                // world builder version
                builder.Register<SystemType>(
                    container => container.Resolve<InterfacedSystemFactory<SystemType, InterfaceType>>().ResolveSystem(),
                    Lifetime.Transient);

                // public version
                builder.Register<InterfaceType>(
                   container => container.Resolve<InterfacedSystemFactory<SystemType, InterfaceType>>().ResolveInterface(),
                   Lifetime.Transient);
            }
        }

        internal sealed class SystemsInitializer : ISystemsOperator
        {
            private readonly MorpehSystemInstallHandler resolver;

            public SystemsInitializer(IObjectResolver resolver)
            {
                this.resolver = resolver.Resolve<MorpehSystemInstallHandler>();
            }

            public void AddSystemWithInterface<SystemType, InterfaceType>(SystemGroupOrder order)
                where SystemType : class, ISystem, InterfaceType
                => AddSystem<SystemType>(order);

            public void AddSystem<T>(SystemGroupOrder order)
                where T : class, ISystem
            {
                resolver.AddSystem<T>(order);
            }
        }




        protected abstract void Configure(ISystemsOperator installer);


        // 1. Bind systems into container to resolve dependencies
        public void InstallDependencies(IContainerBuilder builder)
        {
            Configure(new ContainerSystemsBinder(builder));
        }

        // 2. Add systems with fulfilled dependencies into ECS World
        public void Initialize(IObjectResolver resolver)
        {
            Configure(new SystemsInitializer(resolver));
        }
    }
}
