using System;
using System.Collections.Generic;
using Scellecs.Morpeh;
using VContainer;

namespace ZE.MechBattle.Ecs
{
    public abstract class FeatureSystemsInstallQueue : IFeatureInstaller
    {
        // generated by ChatGPT
        public interface ISystemsOperator
        {
            void AddSystem<T>(SystemGroupOrder order)
                where T : class, ISystem;

            void AddInitializer<T>(SystemGroupOrder order)
                where T : class, IInitializer;
        }

        internal sealed class ContainerSystemsBinder : ISystemsOperator
        {
            private readonly IContainerBuilder builder;

            public ContainerSystemsBinder(IContainerBuilder builder)
            {
                this.builder = builder;
            }

            public void AddSystem<T>(SystemGroupOrder order)
                where T : class, ISystem
            {
                builder.Register<T>(Lifetime.Scoped);
            }

            public void AddInitializer<T>(SystemGroupOrder order)
                where T : class, IInitializer
            {
                builder.Register<T>(Lifetime.Transient);
            }
        }

        internal sealed class SystemsInitializer : ISystemsOperator
        {
            private readonly MorpehSystemInstallHandler resolver;

            public SystemsInitializer(IObjectResolver resolver)
            {
                this.resolver = resolver.Resolve<MorpehSystemInstallHandler>();
            }

            public void AddSystem<T>(SystemGroupOrder order)
                where T : class, ISystem
            {
                resolver.AddSystem<T>(order);
            }

            public void AddInitializer<T>(SystemGroupOrder order)
                where T : class, IInitializer
            {
                resolver.AddInitializer<T>(order);
            }
        }




        protected abstract void Configure(ISystemsOperator installer);


        // 1. Bind systems into container to resolve dependencies
        public void InstallDependencies(IContainerBuilder builder)
        {
            Configure(new ContainerSystemsBinder(builder));
        }

        // 2. Add systems with fulfilled dependencies into ECS World
        public void Initialize(IObjectResolver resolver)
        {
            Configure(new SystemsInitializer(resolver));
        }

        public void PreloadResources(IObjectResolver globalContainerResolver) { }
    }
}
