using Unity.Mathematics;
using Unity.Burst;

namespace ZE.MechBattle.Navigation
{
    // generated by Google AI
    [BurstCompile]
    public struct HexRadiusEnumerator
    {
        private readonly int2 _center;
        private readonly int _radius;
        private int _q;
        private int _r;
        private bool _started;

        public HexRadiusEnumerator(int2 center, int radius)
        {
            _center = center;
            _radius = radius;
            _q = -radius;
            _r = math.max(-radius, -_q - radius);
            _started = false;
        }

        public int2 Current => new int2(_center.x + _q, _center.y + _r);

        public bool MoveNext()
        {
            if (!_started)
            {
                _started = true;
                return _radius >= 0;
            }

            if (_r < math.min(_radius, -_q + _radius))
            {
                _r++;
                return true;
            }

            if (_q < _radius)
            {
                _q++;
                _r = math.max(-_radius, -_q - _radius);
                return true;
            }

            return false;
        }

        public HexRadiusEnumerator GetEnumerator() => this;
    }

}
