using System;
using System.IO;
using UnityEditor;
using UnityEngine;
using ZE.MechBattle.Vfx;

namespace ZE.MechBattle.Editor
{
    public static class ShowScriptablesMenu
    {
        private const string SCRIPTABLES_MENU = "Scriptables/";
        private const string SCRIPTABLES_FOLDER = "Scriptables/";

        [MenuItem(SCRIPTABLES_MENU + "ProjectilesData")]        
        private static void SelectProjectilesData() => SelectScriptable<ProjectilesData>();

        [MenuItem(SCRIPTABLES_MENU + "VfxData")]
        private static void SelectVfxData() => SelectScriptable<VfxData>();

        [MenuItem(SCRIPTABLES_MENU + "Open Unit Configs")]
        private static void OpenUnitConfigs() => OpenFolder("UnitConfigs");

        [MenuItem(SCRIPTABLES_MENU + "Open Weapon Configs")]
        private static void OpenWeaponConfigs() => OpenFolder("WeaponConfigs");

        private static void SelectScriptable<T>() where T : ScriptableObject
        {
            var name = typeof(T).Name;
            T asset = UnityEditor.AssetDatabase.LoadAssetAtPath<T>($"Assets/Game/Resources/Scriptables/{name}.asset");
            if (asset == null)
                UnityEngine.Debug.LogError(name + " scriptable not exist");
            else
                UnityEditor.Selection.activeObject = asset;
        }

        private static void OpenFolder(string folderName) 
        {
            var folderPath = "Assets/Game/Resources/" + folderName;
            UnityEngine.Object folderObj = AssetDatabase.LoadAssetAtPath<DefaultAsset>(folderPath);

            if (folderObj == null)
                UnityEngine.Debug.LogError(folderName + " folder not exist");
            else
            {
                // generated by Google AI
                EditorUtility.FocusProjectWindow();

                try
                {
                    // 3. Через рефлексию находим активное окно ProjectBrowser и вызываем вход в папку
                    Type projectBrowserType = Type.GetType("UnityEditor.ProjectBrowser,UnityEditor");

                    // Находим последнее активное окно Project
                    var lastProjectBrowser = projectBrowserType.GetField("s_LastInteractedProjectBrowser",
                        System.Reflection.BindingFlags.Static | System.Reflection.BindingFlags.Public).GetValue(null);

                    if (lastProjectBrowser == null)
                    {
                        // Если окон нет, принудительно открываем одно
                        lastProjectBrowser = EditorWindow.GetWindow(projectBrowserType);
                    }

                    // Находим приватный метод перехода в папку
                    var showFolderContentsMethod = projectBrowserType.GetMethod("ShowFolderContents",
                        System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance);

                    // Вызываем метод, передавая ID папки
                    showFolderContentsMethod.Invoke(lastProjectBrowser, new object[] { folderObj.GetInstanceID(), true });
                }
                catch (Exception e)
                {
                    // Если рефлексия не сработала, используем безопасный стандартный фокус (он выделит ее снаружи)
                    Selection.activeObject = folderObj;
                    EditorGUIUtility.PingObject(folderObj);
                    Debug.LogWarning($"Не удалось войти внутрь папки через ShowFolderContents: {e.Message}");
                }
            }    
        }
    }

}
