using System;
using System.IO;
using UnityEditor;
using UnityEngine;
using ZE.MechBattle.Vfx;

namespace ZE.MechBattle.Editor
{
    public static class ShowScriptablesMenu
    {
        private const string SCRIPTABLES_MENU = DirectoryConstants.SCRIPTABLES_FOLDER;
        private const string SCRIPTABLES_FOLDER = SCRIPTABLES_MENU;

        [MenuItem(SCRIPTABLES_MENU + "/Features")]
        private static void SelectFeatureModulesList() => SelectScriptable<FeaturesModulesList>();

        [MenuItem(SCRIPTABLES_MENU + "/ProjectilesData")]        
        private static void SelectProjectilesData() => SelectScriptable<ProjectilesData>();

        [MenuItem(SCRIPTABLES_MENU + "/VfxData")]
        private static void SelectVfxData() => SelectScriptable<VfxData>();
        [MenuItem(SCRIPTABLES_MENU + "/CameraSettings")]
        private static void SelectCameraSettings() => SelectScriptable<CameraSettings>();


        [MenuItem(SCRIPTABLES_MENU + "/Open Unit Configs")]
        private static void OpenUnitConfigs() => OpenFolder("UnitConfigs");

        [MenuItem(SCRIPTABLES_MENU + "/Open Weapon Configs")]
        private static void OpenWeaponConfigs() => OpenFolder("WeaponConfigs");

        private static void SelectScriptable<T>() where T : ScriptableObject
        {
            var name = typeof(T).Name;
            T asset = UnityEditor.AssetDatabase.LoadAssetAtPath<T>($"Assets/Game/Resources/{SCRIPTABLES_FOLDER}/{name}.asset");
            if (asset == null)
                UnityEngine.Debug.LogError(name + " scriptable not exist");
            else
                UnityEditor.Selection.activeObject = asset;
        }

        private static void OpenFolder(string folderName) 
        {
            var folderPath = $"Assets/Game/Resources/{SCRIPTABLES_FOLDER}/{folderName}";
            UnityEngine.Object folderObj = AssetDatabase.LoadAssetAtPath<DefaultAsset>(folderPath);

            if (folderObj == null)
                UnityEngine.Debug.LogError(folderName + " folder not exist");
            else
            {
                // generated by Google AI
                EditorUtility.FocusProjectWindow();

                try
                {
                    Type projectBrowserType = Type.GetType("UnityEditor.ProjectBrowser,UnityEditor");
                    var lastProjectBrowser = projectBrowserType.GetField("s_LastInteractedProjectBrowser",
                        System.Reflection.BindingFlags.Static | System.Reflection.BindingFlags.Public).GetValue(null);

                    if (lastProjectBrowser == null)
                    {
                        lastProjectBrowser = EditorWindow.GetWindow(projectBrowserType);
                    }

                    var showFolderContentsMethod = projectBrowserType.GetMethod("ShowFolderContents",
                        System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance);

                    showFolderContentsMethod.Invoke(lastProjectBrowser, new object[] { folderObj.GetInstanceID(), true });
                }
                catch (Exception e)
                {
                    Selection.activeObject = folderObj;
                    EditorGUIUtility.PingObject(folderObj);
                    Debug.LogWarning($"Cannot enter ShowFolderContents: {e.Message}");
                }
            }    
        }
    }

}
