using System;
using UnityEngine;
using Unity.Jobs;
using Unity.Collections;
using Unity.Burst;
using Unity.Mathematics;

namespace ZE.MechBattle.Navigation
{
    public struct RefinedTriangleRaycastData
    {
        public int ObstacledCellsCount;

        public int GroundCastsCount;
        public float AverageGroundHeight;

        public float PinnacleHeight;
        public float LeftBasisHeight;
        public float RightBasisHeight;

        public short GetResultingAverageHeight() => (short)math.round(AverageGroundHeight);
        public float AddHeightAndRecalculate(float newHeight) =>
            (AverageGroundHeight * GroundCastsCount + newHeight) / (GroundCastsCount + 1);

        public float GetHeight(TriangleHeightMeasurePoint param)
        {
            switch(param)
            {
                case TriangleHeightMeasurePoint.Pinnacle: return PinnacleHeight;
                case TriangleHeightMeasurePoint.LeftBasis: return LeftBasisHeight;
                case TriangleHeightMeasurePoint.RightBasis: return RightBasisHeight;
                default: return AverageGroundHeight;
            }
        }
    }

    [BurstCompile]
    public struct RefineNavRaycastDataJob : IJobParallelFor
    {
        // length: hex radius * hex radius * 6 * raycasts per triangle (triangle raycasts)
        [ReadOnly] public NativeArray<RaycastHit>.ReadOnly WalkableHits;
        [ReadOnly] public NativeArray<RaycastHit>.ReadOnly ObstacleHits;

        // length: hex radius * hex radius * 6 (triangles)
        [ReadOnly] public NativeBitArray IsPeakData;
        public NativeArray<RefinedTriangleRaycastData> RefinedData;

        public NavigationHexPosition HexPos;
        public int HexRadius;
        public int RaycastsPerTriangle;

        public int PeakLeftBasisIndex;
        public int PeakRightBasisIndex;
        public int ValleyLeftBasisIndex;
        public int ValleyRightBasisIndex;

        public float MaxHeightDifference;
        public int RansacIterationsCount;

        // per-triangle operation
        // why: parallel writing in RefinedData[index] per iteration
        // (opposing to per-raycast operation, where write index != index (raycast index))
        public void Execute(int triangleIndex)
        {
            var resultingData = new RefinedTriangleRaycastData();
            var readIndex = triangleIndex * RaycastsPerTriangle;

            Span<bool> walkablesHitMask = stackalloc bool[RaycastsPerTriangle];
            Span<float> heights = stackalloc float[RaycastsPerTriangle];

            for (var i = 0; i < RaycastsPerTriangle; i++)
            {
                var walkableHit = WalkableHits[readIndex + i];
                var isWalkable = walkableHit.colliderInstanceID != 0;

                walkablesHitMask[i] = isWalkable;
                var walkableHeight = isWalkable ? walkableHit.point.y : NavigationConstants.DEFAULT_HEIGHT;
                resultingData.GroundCastsCount += isWalkable ? 1 : 0;
                heights[i] = walkableHeight;               
                
                var obstacleHit = ObstacleHits[readIndex + i];
                var isObstacled = obstacleHit.colliderInstanceID != 0;
                resultingData.ObstacledCellsCount += isObstacled ? 1 : 0;
            }

            // preparing corner heights

            var isPeakTriangle = IsPeakData.IsSet(triangleIndex);            
            const int PINNACLE_INDEX = 0;
            var leftBasisIndex = isPeakTriangle ? PeakLeftBasisIndex : ValleyLeftBasisIndex;
            var rightBasisIndex = isPeakTriangle ? PeakRightBasisIndex : ValleyRightBasisIndex;

            #if UNITY_EDITOR
            if (leftBasisIndex >= RaycastsPerTriangle || rightBasisIndex >= RaycastsPerTriangle)
            {
                Debug.LogError($"failed: {leftBasisIndex} : {rightBasisIndex} / {RaycastsPerTriangle}");
            }
#endif

            RansacHeightsRefinement(heights, 0.1f);
            var sum = 0f;
            for (var i = 0; i < RaycastsPerTriangle; i++)
            {
                sum += heights[i];
            }
            resultingData.AverageGroundHeight = sum / RaycastsPerTriangle;
            resultingData.PinnacleHeight = heights[ PINNACLE_INDEX];
            resultingData.LeftBasisHeight = heights[ leftBasisIndex];
            resultingData.RightBasisHeight = heights[ rightBasisIndex];

            RefinedData[triangleIndex] = resultingData;

            if (false)
            {
                Debug.Log(isPeakTriangle);
                for (var i = 0; i <RaycastsPerTriangle; i++)
                {
                    var pos = WalkableHits[i].point;
                    var height = heights[i];
                    UnityEngine.Debug.Log($"{i} : ({pos.x},{pos.y} -> {height}, {pos.z}");
                }
            }
        }

        // generated by Google AI
        private void RansacHeightsRefinement(Span<float> heights, float threshold)
        {
            float4 bestPlane = float4.zero;
            int maxInliers = -1;

            var rng = new Unity.Mathematics.Random((uint)this.GetHashCode());

            for (int i = 0; i < RansacIterationsCount; i++)
            {
                // 1. Выбираем 3 случайные точки
                int i1 = rng.NextInt(0, RaycastsPerTriangle);
                int i2 = rng.NextInt(0, RaycastsPerTriangle);
                int i3 = rng.NextInt(0, RaycastsPerTriangle);

                // Собираем float3, используя XZ из хитов и Y из нашего массива высот
                float3 p1 = new float3(WalkableHits[i1].point.x, heights[i1], WalkableHits[i1].point.z);
                float3 p2 = new float3(WalkableHits[i2].point.x, heights[i2], WalkableHits[i2].point.z);
                float3 p3 = new float3(WalkableHits[i3].point.x, heights[i3], WalkableHits[i3].point.z);

                // Проверка на коллинеарность (чтобы не получить нулевой вектор нормали)
                float3 v1 = p2 - p1;
                float3 v2 = p3 - p1;
                float3 cross = math.cross(v1, v2);

                if (math.lengthsq(cross) < 0.0001f) continue;                

                float3 normal = math.normalize(cross);
                if (math.abs(normal.y) < 0.707f) continue;


                float d = -math.dot(normal, p1);
                float4 currentPlane = new float4(normal, d);

                // 2. Подсчет инлайеров
                int inliersCount = 0;
                for (int j = 0; j < RaycastsPerTriangle; j++)
                {
                    float3 pCurr = new float3(WalkableHits[j].point.x, heights[j], WalkableHits[j].point.z);
                    float dist = math.abs(math.dot(currentPlane.xyz, pCurr) + currentPlane.w);

                    if (dist < threshold) inliersCount++;
                }

                if (inliersCount > maxInliers)
                {
                    maxInliers = inliersCount;
                    bestPlane = currentPlane;
                }
            }

            // 3. Выравнивание (только для тех, кто подошел под плоскость)
            if (maxInliers > 0)
            {
                for (int j = 0; j < RaycastsPerTriangle; j++)
                {
                    float3 p = new float3(WalkableHits[j].point.x, heights[j], WalkableHits[j].point.z);

                    // ВСЕ точки принудительно сажаем на найденную плоскость
                    if (math.abs(bestPlane.y) > 0.0001f)
                    {
                        float newY = -(bestPlane.x * p.x + bestPlane.z * p.z + bestPlane.w) / bestPlane.y;
                        heights[j] = newY;
                    }
                }
            }

        }

    }
}
