using System;
using UnityEngine;
using Unity.Jobs;
using Unity.Collections;
using Unity.Burst;
using Unity.Mathematics;

namespace ZE.MechBattle.Navigation
{
    public struct RefinedTriangleRaycastData
    {
        public int ObstacledCellsCount;

        public int GroundCastsCount;
        public float AverageGroundHeight;

        public float PinnacleHeight;
        public float LeftBasisHeight;
        public float RightBasisHeight;

        public short GetResultingAverageHeight() => (short)math.round(AverageGroundHeight);
        public float AddHeightAndRecalculate(float newHeight) =>
            (AverageGroundHeight * GroundCastsCount + newHeight) / (GroundCastsCount + 1);

        public float GetHeight(TriangleHeightMeasurePoint param)
        {
            switch(param)
            {
                case TriangleHeightMeasurePoint.Pinnacle: return PinnacleHeight;
                case TriangleHeightMeasurePoint.LeftBasis: return LeftBasisHeight;
                case TriangleHeightMeasurePoint.RightBasis: return RightBasisHeight;
                default: return AverageGroundHeight;
            }
        }
    }

    [BurstCompile]
    public struct RefineNavRaycastDataJob : IJobParallelFor
    {
        // length: hex radius * hex radius * 6 * raycasts per triangle (triangle raycasts)
        [ReadOnly] public NativeArray<RaycastHit>.ReadOnly WalkableHits;
        [ReadOnly] public NativeArray<RaycastHit>.ReadOnly ObstacleHits;

        // length: hex radius * hex radius * 6 (triangles)
        [ReadOnly] public NativeBitArray.ReadOnly IsPeakData;
        public NativeArray<RefinedTriangleRaycastData> RefinedData;

        public NavigationHexPosition HexPos;
        public int HexRadius;
        public int RaycastsPerTriangle;

        public int PeakLeftBasisIndex;
        public int PeakRightBasisIndex;
        public int ValleyLeftBasisIndex;
        public int ValleyRightBasisIndex;

        public float MaxHeightDifference;
        public int RansacIterationsCount;
        public float RansacThreshold;

        // per-triangle operation
        // why: parallel writing in RefinedData[index] per iteration
        // (opposing to per-raycast operation, where write index != index (raycast index))
        public void Execute(int triangleIndex)
        {
            var resultingData = new RefinedTriangleRaycastData();
            var readIndex = triangleIndex * RaycastsPerTriangle;

            Span<bool> walkablesHitMask = stackalloc bool[RaycastsPerTriangle];
            Span<float> heights = stackalloc float[RaycastsPerTriangle];

            for (var i = 0; i < RaycastsPerTriangle; i++)
            {
                var walkableHit = WalkableHits[readIndex + i];
                var isWalkable = walkableHit.colliderInstanceID != 0;

                walkablesHitMask[i] = isWalkable;
                var walkableHeight = isWalkable ? walkableHit.point.y : NavigationConstants.DEFAULT_HEIGHT;
                resultingData.GroundCastsCount += isWalkable ? 1 : 0;
                heights[i] = walkableHeight;               
                
                var obstacleHit = ObstacleHits[readIndex + i];
                var isObstacled = obstacleHit.colliderInstanceID != 0;
                resultingData.ObstacledCellsCount += isObstacled ? 1 : 0;
            }

            // preparing corner heights

            var isPeakTriangle = IsPeakData.IsSet(triangleIndex);            
            const int PINNACLE_INDEX = 0;
            var leftBasisIndex = isPeakTriangle ? PeakLeftBasisIndex : ValleyLeftBasisIndex;
            var rightBasisIndex = isPeakTriangle ? PeakRightBasisIndex : ValleyRightBasisIndex;

            #if UNITY_EDITOR
            if (leftBasisIndex >= RaycastsPerTriangle || rightBasisIndex >= RaycastsPerTriangle)
            {
                Debug.LogError($"failed: {leftBasisIndex} : {rightBasisIndex} / {RaycastsPerTriangle}");
            }
#endif

            RansacWithNormals(triangleIndex * RaycastsPerTriangle, heights);
            var sum = 0f;
            for (var i = 0; i < RaycastsPerTriangle; i++)
            {
                sum += heights[i];
            }
            resultingData.AverageGroundHeight = sum / RaycastsPerTriangle;
            resultingData.PinnacleHeight = heights[ PINNACLE_INDEX];
            resultingData.LeftBasisHeight = heights[ leftBasisIndex];
            resultingData.RightBasisHeight = heights[ rightBasisIndex];

            RefinedData[triangleIndex] = resultingData;
        }

        // generated by Google AI
        public void RansacWithNormals(int startIndex, Span<float> heights)
        {
            float4 bestPlane = new float4(0, 1, 0, -heights[0]); 
            int maxInliers = -1;
            var rng = new Unity.Mathematics.Random((uint)startIndex + 1);

            for (int i = 0; i < RansacIterationsCount; i++)
            {
                int idx = rng.NextInt(0, RaycastsPerTriangle);
                var hit = WalkableHits[startIndex + idx];
                if (hit.colliderInstanceID == 0) continue;

                float3 p = new float3(hit.point.x, heights[idx], hit.point.z);
                float3 n = hit.normal;

                if (math.abs(n.y) < 0.01f) continue;

                float4 currentPlane = new float4(n, -math.dot(n, p));

                int inliersCount = 0;
                for (int j = 0; j < RaycastsPerTriangle; j++)
                {
                    var h = WalkableHits[startIndex + j];
                    float3 pCurr = new float3(h.point.x, heights[j], h.point.z);

                    float dist = math.abs(math.dot(currentPlane.xyz, pCurr) + currentPlane.w);
                    float normalDiff = 1f - math.dot(currentPlane.xyz, h.normal);

                    if (dist < RansacThreshold && normalDiff < 0.1f)
                        inliersCount++;
                }

                if (inliersCount > maxInliers)
                {
                    maxInliers = inliersCount;
                    bestPlane = currentPlane;
                }
            }

            if (maxInliers > 0)
            {
                for (int j = 0; j < RaycastsPerTriangle; j++)
                {
                    var h = WalkableHits[startIndex + j];
                    float3 p = new float3(h.point.x, heights[j], h.point.z);
                    if (math.abs(bestPlane.y) > 0.001f)
                    {
                        heights[j] = -(bestPlane.x * p.x + bestPlane.z * p.z + bestPlane.w) / bestPlane.y;
                    }
                }
            }
        }
    }
}
