using System;
using Unity.Mathematics;
using TriInspector;

namespace ZE.MechBattle
{
    [Serializable]
    public struct ForwardRotationLimits
    {
        public bool2 LimitAxleRotation;

        [ShowIf(nameof(XAxleLimited))]  public float XAngleDegreesLimit;
        [ShowIf(nameof(YAxleLimited))]  public float YAngleDegreesLimit;

        public float2 GetDotLimits() =>
            new(
                XAxleLimited ? GetDotLimit(new(XAngleDegreesLimit, 0f, 0f)) : -1.01f,
                YAxleLimited ? GetDotLimit(new(0f, YAngleDegreesLimit, 0f)) : -1.01f
                );

        private bool XAxleLimited => LimitAxleRotation.x;
        private bool YAxleLimited => LimitAxleRotation.y;

        private float GetDotLimit(float3 rotationDegrees)
        {
            var rot = quaternion.Euler(math.radians(rotationDegrees));
            return DotWithForward(rot);
        }

        // generated by Deepseek
        private float DotWithForward(quaternion q)
        {
            float4 val = q.value;
            // = 2*(w² + z²) - 1
            return 2 * (val.w * val.w + val.z * val.z) - 1;
        }

    }
}
