using System;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

namespace ZE.MechBattle
{
    // generated by Google AI

    [RequireComponent(typeof(CanvasRenderer))]
    public class UIQuadGridRenderer : Graphic
    {
        [Header("Grid Settings")]
        [SerializeField] private float quadSize = 8f; 
        [SerializeField] private float spacing = 2f;

        [Header("Color Settings")]
        [SerializeField] private Gradient healthColorGradient;
        [SerializeField] private Color32 emptyColor = Color.red;

        [Header("State")]
        [Range(0f, 1f)]
        [SerializeField] private float fillValue = 1f;
        [SerializeField] private int seed = 42;

        private List<int> ShuffledIndices = new List<int>();
        private int lastSeed = -1;

        public float Value
        {
            get => fillValue;
            set { fillValue = Mathf.Clamp01(value); SetVerticesDirty(); }
        }

        public int Seed
        {
            get => seed;
            set { if (seed != value) { seed = value; lastSeed = -1; SetVerticesDirty(); } }
        }

        protected override void OnPopulateMesh(VertexHelper vh)
        {

            vh.Clear();

            Rect rect = rectTransform.rect;

            int cols = Mathf.FloorToInt((rect.width + spacing) / (quadSize + spacing));
            int rows = Mathf.FloorToInt((rect.height + spacing) / (quadSize + spacing));

            int totalQuads = cols * rows;
            if (totalQuads <= 0) return;

            UpdateShuffledIndices(totalQuads);

            int healthCount = Mathf.RoundToInt(fillValue * totalQuads);

            bool[] isHealth = new bool[totalQuads];
            for (int i = 0; i < healthCount; i++)
            {
                int targetIndex = ShuffledIndices[i];
                isHealth[targetIndex] = true;
            }

            float totalWidth = cols * quadSize + (cols - 1) * spacing;
            float totalHeight = rows * quadSize + (rows - 1) * spacing;

            Vector2 startPos = new Vector2(
                rect.xMin + (rect.width - totalWidth) * 0.5f,
                rect.yMin + (rect.height - totalHeight) * 0.5f
            );

            int quadCounter = 0;
            var activeColor = healthColorGradient.Evaluate(Value);

            for (int r = 0; r < rows; r++)
            {
                for (int c = 0; c < cols; c++)
                {
                    float x = startPos.x + c * (quadSize + spacing);
                    float y = startPos.y + r * (quadSize + spacing);

                    Color32 color = isHealth[quadCounter] ? activeColor : emptyColor;

                    UIVertex v0 = CreateVertex(new Vector3(x, y, 0), color);
                    UIVertex v1 = CreateVertex(new Vector3(x, y + quadSize, 0), color);
                    UIVertex v2 = CreateVertex(new Vector3(x + quadSize, y + quadSize, 0), color);
                    UIVertex v3 = CreateVertex(new Vector3(x + quadSize, y, 0), color);

                    int startIndex = vh.currentVertCount;
                    vh.AddVert(v0);
                    vh.AddVert(v1);
                    vh.AddVert(v2);
                    vh.AddVert(v3);

                    vh.AddTriangle(startIndex, startIndex + 1, startIndex + 2);
                    vh.AddTriangle(startIndex, startIndex + 2, startIndex + 3);

                    quadCounter++;
                }
            }
        }

        private void UpdateShuffledIndices(int totalQuads)
        {
            if (ShuffledIndices.Count == totalQuads && seed == lastSeed) return;

            ShuffledIndices.Clear();
            for (int i = 0; i < totalQuads; i++)
            {
                ShuffledIndices.Add(i);
            }

            System.Random rand = new System.Random(seed);
            for (int i = ShuffledIndices.Count - 1; i > 0; i--)
            {
                int j = rand.Next(i + 1);
                int temp = ShuffledIndices[i];
                ShuffledIndices[i] = ShuffledIndices[j];
                ShuffledIndices[j] = temp;
            }
            lastSeed = seed;
        }

        private UIVertex CreateVertex(Vector3 position, Color32 color)
        {
            UIVertex vertex = UIVertex.simpleVert;
            vertex.position = position;
            vertex.color = color;
            return vertex;
        }

        protected override void OnRectTransformDimensionsChange()
        {
            base.OnRectTransformDimensionsChange();
            SetVerticesDirty();
        }
    }

}
