using System.Runtime.CompilerServices;
using UnityEngine;
using Unity.Mathematics;
using System;
using Unity.Collections;
using Unity.Burst;


namespace ZE.MechBattle.Navigation
{
    // generated by Deepseek
    public struct CellPassabilityData
    {
        public const int SERIALIZATION_SIZE = sizeof(ushort);
        private ushort _data;

        // Layout: [1 bit IsPassable] [12 bits NeighboursMask] [3 bits EntranceCost]
        // Offset: 0                    1                    13
        private const int PASSABLE_OFFSET = 0;
        private const int NEIGHBOURS_OFFSET = 1;
        private const int COST_OFFSET = 13;

        private const ushort PASSABLE_MASK = 1 << PASSABLE_OFFSET;
        private const ushort NEIGHBOURS_MASK = 0xFFF; // 12 bits
        private const ushort COST_MASK = 0x7; // 3 bits

        public CellPassabilityData(bool isPassable, int neighboursMask, sbyte entranceCost)
        {
            _data = 0;
            IsPassable = isPassable;
            NeighboursMask = neighboursMask;
            EntranceCost = entranceCost;
        }

        private CellPassabilityData(ushort data)
        {
            _data = data;
        }

        public bool IsPassable
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => (_data & PASSABLE_MASK) != 0;
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            private set => _data = (ushort)((_data & ~PASSABLE_MASK) | (value ? PASSABLE_MASK : 0));
        }

        public int NeighboursMask
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => (_data >> NEIGHBOURS_OFFSET) & NEIGHBOURS_MASK;
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            private set => _data = (ushort)((_data & ~(NEIGHBOURS_MASK << NEIGHBOURS_OFFSET))
                                            | ((value & NEIGHBOURS_MASK) << NEIGHBOURS_OFFSET));
        }

        public sbyte EntranceCost
        {
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            get => (sbyte)(((_data >> COST_OFFSET) & COST_MASK) - 4); // Shift -4..3
            [MethodImpl(MethodImplOptions.AggressiveInlining)]
            private set
            {
                int encoded = value + 4; // -4..3 -> 0..7
                _data = (ushort)((_data & ~(COST_MASK << COST_OFFSET))
                                | ((encoded & COST_MASK) << COST_OFFSET));
            }
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public bool IsNeighbourAccessible(int neighbourIndex)
        {
            if ((uint)neighbourIndex >= 12) return false;
            return (NeighboursMask & (1 << neighbourIndex)) != 0;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public void SetNeighbourPassable(int neighbourIndex, bool passable)
        {
            if ((uint)neighbourIndex >= 12) return;
            int mask = 1 << neighbourIndex;
            if (passable)
                NeighboursMask |= mask;
            else
                NeighboursMask &= ~mask;
        }

        [BurstCompile]
        public static void Encode(NativeSlice<byte> buffer, CellPassabilityData data, int offset)
        {
            ByteCoder.WriteShortToBufferLittleEndian(buffer, (short)data._data, offset); 
        }

        [BurstCompile]
        public static CellPassabilityData Decode(NativeSlice<byte> buffer, int offset)
        {
            var data = (ushort)ByteCoder.ReadShortFromBufferLittleEndian(buffer, offset);
            return new(data);
        }

        [BurstCompile]
        public static CellPassabilityData CreateDefaultData(bool isPassable) => new(isPassable, int.MaxValue, NavigationConstants.DEFAULT_TRIANGLE_ENTRANCE_COST);


        /*
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static int GetNeighboursMask(ushort data) => (data >> NEIGHBOURS_OFFSET) & NEIGHBOURS_MASK;

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static sbyte GetEntranceCost(ushort data) => (sbyte)(((data >> COST_OFFSET) & COST_MASK) - 4);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool IsNeighbourPassable(ushort data, int neighbourIndex) =>
            ((uint)neighbourIndex < 12) && ((GetNeighboursMask(data) & (1 << neighbourIndex)) != 0);

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool GetIsPassable(ushort data) => (data & PASSABLE_MASK) != 0;
        */
    }

}
