using System;
using System.Collections.Generic;
using UnityEngine;
using Unity.Burst;
using Unity.Mathematics;
using Unity.Collections;

namespace ZE.MechBattle.Navigation
{
    public unsafe struct CombinedFlowData : IEquatable<CombinedFlowData>
    {

        private fixed int Values[6];

        public FlowMapCellData this[HexEdge edge] => new(Values[(int)edge]);

        public int this[int index] => Values[index];
        public const int SERIALIZATION_LENGTH = sizeof(int) * 6 + CellPassabilityData.SERIALIZATION_SIZE;

        #region equality 
        // generated by Google AI
        public bool Equals(CombinedFlowData other)
        {
            fixed (int* pThis = Values)
            {
                int* pOther = other.Values;

                long* lThis = (long*)pThis;
                long* lOther = (long*)pOther;

                return lThis[0] == lOther[0] &&
                       lThis[1] == lOther[1] &&
                       lThis[2] == lOther[2];
            }
        }

        public override bool Equals(object obj) => obj is CombinedFlowData other && Equals(other);

        public override int GetHashCode()
        {
            fixed (int* p = Values)
            {
                var hash = new HashCode();
                for (int i = 0; i < 6; i++) hash.Add(p[i]);
                return hash.ToHashCode();
            }
        }
        #endregion

        [BurstDiscard]
        public override string ToString()
        {
            var stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append("triangle data: ");
            for (var i = 0; i < 6; i++)
            {
                stringBuilder.AppendLine();
                var edge = (HexEdge)i;
                stringBuilder.Append($"{edge}: ");
                stringBuilder.Append(this[edge].ToString());
            }
            return stringBuilder.ToString();
        }

        public CombinedFlowData(FlowMapCellData[] cells)
        {
            for (var i = 0; i < 6; i++)
            {
                Values[i] = cells[i].Value;
            }
        }

        public CombinedFlowData(
            FlowMapCellData c0, 
            FlowMapCellData c1, 
            FlowMapCellData c2, 
            FlowMapCellData c3, 
            FlowMapCellData c4, 
            FlowMapCellData c5)
        {
            Values[0] = c0.Value;
            Values[1] = c1.Value;
            Values[2] = c2.Value;
            Values[3] = c3.Value;
            Values[4] = c4.Value;
            Values[5] = c5.Value;
        }

        public CombinedFlowData(int c0, int c1, int c2, int c3, int c4, int c5)
        {
            Values[0] = c0;
            Values[1] = c1;
            Values[2] = c2;
            Values[3] = c3;
            Values[4] = c4;
            Values[5] = c5;
        }

        public CombinedFlowData(ReadOnlySpan<int> cells)
        {
            for (var i = 0; i < 6; i++)
            {
                Values[i] = cells[i];
            }
        }


        // encodes if edge can be reached from current cell (if distance to edge is not invalid)
        public HexEdgesMask GetCombinedEdgeAccessMask()
        {
            var mask = 0;
            for (var i = 0; i < 6; i++)
            {
                mask |= ((Values[i] & FlowMapCellData.DISTANCE_MASK) == FlowMapCellData.INVALID_EXIT_DISTANCE) ? 0 : (1 << i);
            }
            return new(mask);
        }


        [BurstCompile]
        public static CombinedFlowData CreateDefaultCell(
            IntTriangularPos pos, 
            INavigationMap map)
        {
            var cell = new CombinedFlowData();
            var hexCenter = new NavigationHexPosition(pos, map).TriangularCenterPos;
            var radius = map.TrianglesPerHexEdge;

            for (var i = 0; i < 6; i++)
            {
                var edge = (HexEdge)i;
                var logic = new UniversalEdgeLimitLogic(edge, hexCenter, radius);

                var edgeCenter = edge.GetEdgeCenterPos(hexCenter, radius);
                var rawDist = (ushort)TriangularMath.CalculateDistance(pos, edgeCenter);
                var finalDist = (ushort)math.select(rawDist, 0, logic.IsEdgeTriangle(pos));

                var hexSector = TriangularMath.DefineSector(pos, map.HexEdgeSize, radius, map.TriangleHeight);
                var dir = hexSector.GetDefaultFlowDirection(edge, pos.IsPeak);

                cell.Values[i] = new FlowMapCellData(dir, finalDist).Value;
            }
            return cell;
        }
    }
}
