using System;
using System.Runtime.InteropServices;
using Unity.Mathematics;

namespace ZE.MechBattle.Navigation
{
    // generated by Google AI

    [Serializable]
    [StructLayout(LayoutKind.Sequential)]
    public struct float6 : IEquatable<float6>
    {
        public float f1, f2, f3, f4, f5, f6;

        public float6(float f1, float f2, float f3, float f4, float f5, float f6)
        {
            this.f1 = f1;
            this.f2 = f2;
            this.f3 = f3;
            this.f4 = f4;
            this.f5 = f5;
            this.f6 = f6;
        }

        public float6(float x)
        {
            f1 = f2 = f3 = f4 = f5 = f6 = x;
        }

        public readonly bool Equals(float6 other)
        {
            return f1 == other.f1 &&
                   f2 == other.f2 &&
                   f3 == other.f3 &&
                   f4 == other.f4 &&
                   f5 == other.f5 &&
                   f6 == other.f6;
        }

        public override readonly bool Equals(object obj) => obj is float6 other && Equals(other);

        public override readonly int GetHashCode()
        {
            uint h1 = math.hash(new float4(f1, f2, f3, f4));
            uint h2 = math.hash(new float2(f5, f6));

            return (int)math.hash(new uint2(h1, h2));
        }

        public static bool operator ==(float6 left, float6 right) => left.Equals(right);
        public static bool operator !=(float6 left, float6 right) => !left.Equals(right);

        public override readonly string ToString() => $"float6({f1}, {f2}, {f3}, {f4}, {f5}, {f6})";
    }

}
