using System;
using System.Collections.Generic;
using UnityEngine;
using Unity.Burst;
using Unity.Mathematics;
using Unity.Collections;

namespace ZE.MechBattle.Navigation
{
    public unsafe struct FlowMapCombinedCell : IEquatable<FlowMapCombinedCell>
    {
        public bool IsPassable => _triangleData.IsPassable;
        public short Height => _triangleData.Height;
        public sbyte EntranceCost => _triangleData.EntranceCost;        
        public TriangleNavData TriangleData => _triangleData;

        private fixed int Values[6];
        private TriangleNavData _triangleData;

        public FlowMapCellData this[HexEdge edge] => new(Values[(int)edge]);

        public int this[int index] => Values[index];
        public const int SERIALIZATION_LENGTH = sizeof(int) * 6 + TriangleNavData.SERIALIZATION_SIZE;

        #region equality 
        // generated by Google AI
        public bool Equals(FlowMapCombinedCell other)
        {
            if (!_triangleData.Equals(other._triangleData))
                return false;

            fixed (int* pThis = Values)
            {
                int* pOther = other.Values;

                long* lThis = (long*)pThis;
                long* lOther = (long*)pOther;

                return lThis[0] == lOther[0] &&
                       lThis[1] == lOther[1] &&
                       lThis[2] == lOther[2];
            }
        }

        public override bool Equals(object obj) => obj is FlowMapCombinedCell other && Equals(other);

        public override int GetHashCode()
        {
            fixed (int* p = Values)
            {
                var hash = new HashCode();
                hash.Add(_triangleData);
                for (int i = 0; i < 6; i++) hash.Add(p[i]);
                return hash.ToHashCode();
            }
        }
        #endregion

        [BurstDiscard]
        public override string ToString()
        {
            var stringBuilder = new System.Text.StringBuilder();
            stringBuilder.Append("triangle data: ");
            stringBuilder.Append(_triangleData.ToString());
            for (var i = 0; i < 6; i++)
            {
                stringBuilder.AppendLine();
                var edge = (HexEdge)i;
                stringBuilder.Append($"{edge}: ");
                stringBuilder.Append(this[edge].ToString());
            }
            return stringBuilder.ToString();
        }

        public FlowMapCombinedCell(FlowMapCellData[] cells, TriangleNavData triangleData)
        {
            for (var i = 0; i < 6; i++)
            {
                Values[i] = cells[i].Value;
            }
            _triangleData = triangleData;
        }

        public FlowMapCombinedCell(
            FlowMapCellData c0, 
            FlowMapCellData c1, 
            FlowMapCellData c2, 
            FlowMapCellData c3, 
            FlowMapCellData c4, 
            FlowMapCellData c5,
            TriangleNavData triangleData)
        {
            Values[0] = c0.Value;
            Values[1] = c1.Value;
            Values[2] = c2.Value;
            Values[3] = c3.Value;
            Values[4] = c4.Value;
            Values[5] = c5.Value;
            _triangleData = triangleData;
        }

        public FlowMapCombinedCell(int c0, int c1, int c2, int c3, int c4, int c5, TriangleNavData triangleData)
        {
            Values[0] = c0;
            Values[1] = c1;
            Values[2] = c2;
            Values[3] = c3;
            Values[4] = c4;
            Values[5] = c5;
            _triangleData = triangleData;
        }

        public FlowMapCombinedCell(ReadOnlySpan<int> cells, TriangleNavData triangleData)
        {
            for (var i = 0; i < 6; i++)
            {
                Values[i] = cells[i];
            }
            _triangleData = triangleData;
        }


        // encodes if edge can be reached from current cell (if distance to edge is not invalid)
        public HexEdgesMask GetCombinedEdgeAccessMask()
        {
            var mask = 0;
            for (var i = 0; i < 6; i++)
            {
                mask |= ((Values[i] & FlowMapCellData.DISTANCE_MASK) == FlowMapCellData.INVALID_EXIT_DISTANCE) ? 0 : (1 << i);
            }
            return new(mask);
        }


        [BurstCompile]
        public static FlowMapCombinedCell CreateDefaultCell(
            IntTriangularPos pos, 
            TriangleNavData triangleData,
            INavigationMap map)
        {
            var cell = new FlowMapCombinedCell();
            var hexCenter = new NavigationHexPosition(pos, map).TriangularCenterPos;
            var radius = map.TrianglesPerHexEdge;

            for (var i = 0; i < 6; i++)
            {
                var edge = (HexEdge)i;
                var logic = new UniversalEdgeLimitLogic(edge, hexCenter, radius);

                var edgeCenter = edge.GetEdgeCenterPos(hexCenter, radius);
                var rawDist = (ushort)TriangularMath.CalculateDistance(pos, edgeCenter);
                var finalDist = (ushort)math.select(rawDist, 0, logic.IsEdgeTriangle(pos));

                var hexSector = TriangularMath.DefineSector(pos, map.HexEdgeSize, radius, map.TriangleHeight);
                var dir = hexSector.GetDefaultFlowDirection(edge, pos.IsPeak);

                cell.Values[i] = new FlowMapCellData(dir, finalDist).Value;
            }
            cell._triangleData = triangleData;
            return cell;
        }


        [BurstCompile]
        public static void Encode(NativeSlice<byte> buffer, FlowMapCombinedCell combinedCellData, int offset)
        {
            for (var i = 0; i < 6; i++)
            {
                ByteCoder.WriteIntToBufferLittleEndian(buffer, combinedCellData.Values[i], offset + i * 4);
            }
            TriangleNavData.Encode(combinedCellData.TriangleData, buffer, offset + 24);
        }

        [BurstCompile]
        public static FlowMapCombinedCell Decode(NativeSlice<byte> buffer, int offset)
        {
            Span<int> decodedValues = stackalloc int[6];
            for (var i = 0; i < 6; i++)
            {
                decodedValues[i] = ByteCoder.ReadIntFromBufferLittleEndian(buffer, offset + i * 4);
            }
            var triangleData = TriangleNavData.Decode(buffer, offset + 24);
            return new(decodedValues, triangleData);
        }
    }
}
