using System.Runtime.CompilerServices;
using Unity.Collections;
using Unity.Burst;
using Unity.Mathematics;

namespace ZE.MechBattle.Navigation
{
    // Generated by GoogleAI
    // (note: always change to returning a COPY of bitfield after operation, data wont change otherwise)
    public readonly struct HexEdgesAccessMap
    {
        public static HexEdgesAccessMap FullAccessMap => new(new BitField32(uint.MaxValue));
        public static HexEdgesAccessMap NoWayMap => default;
        public BitField32 Data => _data;

        private readonly BitField32 _data;

        public HexEdgesAccessMap(BitField32 data) => _data = data;

        public HexEdgesAccessMap SetConnectionStatus(HexEdge a, HexEdge b, bool isAccessible)
        {
            int index = GetConnectionIndex(a, b);
            var dataCopy = _data;
            if (isAccessible) 
                dataCopy.SetBits(index, true);
            else
                dataCopy.SetBits(index, false);
            return new(dataCopy);
        }

        public bool AreEdgesConnected(HexEdge a, HexEdge b)
        {
            if (a == b) return true;
            return _data.IsSet(GetConnectionIndex(a, b));
        }

        public static int GetConnectionIndex(HexEdge start, HexEdge end)
        {
            var a = (int)start;
            var b = (int)end;
            int min = math.min(a, b);
            int max = math.max(a, b);

            return (min * (11 - min)) / 2 + (max - min - 1);
        }
    }
}
