using System;
using System.Runtime.InteropServices;
using Unity.Mathematics;

namespace ZE.MechBattle.Navigation
{
    // generated by Google AI

    [Serializable]
    [StructLayout(LayoutKind.Sequential)]
    public struct int6 : IEquatable<int6>
    {
        public int f1, f2, f3, f4, f5, f6;

        public int6(int f1, int f2, int f3, int f4, int f5, int f6)
        {
            this.f1 = f1;
            this.f2 = f2;
            this.f3 = f3;
            this.f4 = f4;
            this.f5 = f5;
            this.f6 = f6;
        }

        public int6(int x)
        {
            f1 = f2 = f3 = f4 = f5 = f6 = x;
        }

        public readonly bool Equals(int6 other)
        {
            return f1 == other.f1 &&
                   f2 == other.f2 &&
                   f3 == other.f3 &&
                   f4 == other.f4 &&
                   f5 == other.f5 &&
                   f6 == other.f6;
        }

        public override readonly bool Equals(object obj) => obj is int6 other && Equals(other);

        public override readonly int GetHashCode()
        {
            uint h1 = math.hash(new int4(f1, f2, f3, f4));
            uint h2 = math.hash(new int2(f5, f6));

            return (int)math.hash(new uint2(h1, h2));
        }

        public static bool operator ==(int6 left, int6 right) => left.Equals(right);
        public static bool operator !=(int6 left, int6 right) => !left.Equals(right);

        public override readonly string ToString() => $"int6({f1}, {f2}, {f3}, {f4}, {f5}, {f6})";
    }

}
