using System.Runtime.CompilerServices;
using UnityEngine;
using Unity.Mathematics;

namespace ZE.MechBattle.Navigation
{
    // generated by Google AI

    public readonly struct TriangleNavData
    {
        public readonly int Value;

        private const int IS_VALID_BIT = 31;
        private const int IS_PASSABLE_BIT = 30;
        private const int COST_SHIFT = 16;
        private const int COST_MASK = 0xFF;   
        private const int HEIGHT_MASK = 0xFFFF; 

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public TriangleNavData(bool isPassable, short height, sbyte entranceCost)
        {
            // —борка:
            // 1. Validity bit (31)
            // 2. Passability bit (30)
            // 3. Entrance cost ( 16 - 23)
            // 4. height at lowest 16
            Value = (1 << IS_VALID_BIT) |
                    (math.select(0, 1, isPassable) << IS_PASSABLE_BIT) |
                    ((entranceCost & COST_MASK) << COST_SHIFT) |
                    (height & HEIGHT_MASK);
        }

        public bool IsValid => (Value >> IS_VALID_BIT & 1) != 0;
        public bool IsPassable => (Value >> IS_PASSABLE_BIT & 1) != 0;

        public sbyte EntranceCost => (sbyte)((Value >> COST_SHIFT) & COST_MASK);

        public float Height => (short)(Value & HEIGHT_MASK);

        public static TriangleNavData Empty => default;
        public static TriangleNavData CreateDefaultData(bool isPassable) => new(isPassable, 0,NavigationConstants.DEFAULT_TRIANGLE_ENTRANCE_COST);
    }

}
