using NUnit.Framework;
using Unity.Mathematics;

namespace ZE.MechBattle.Editor.Tests
{
   
    public class LimitedRotationTest
    {
        private const float Epsilon = 0.01f;

        // generated by GoogleAI
        [Test]
        public void GetRotation_CenterInput_ReturnsIdentity()
        {
            // При вводе (0.5, 0.5) объект должен смотреть строго вперед
            float2 input = new float2(0.5f, 0.5f);

            quaternion result = MathExtensions.GetLimitedNormalizedRotation(input, new float2(1f,0f));

            // Итоговый кватернион должен быть равен identity (нет вращения)
            Assert.AreEqual(quaternion.identity.value.x, result.value.x, Epsilon);
            Assert.AreEqual(quaternion.identity.value.y, result.value.y, Epsilon);
            Assert.AreEqual(quaternion.identity.value.z, result.value.z, Epsilon);
            Assert.AreEqual(quaternion.identity.value.w, result.value.w, Epsilon);
        }

        [TestCase(0.866f, 0.866f, 0f, 0f, -30f, -30f)]
        [TestCase(0.866f, 0.866f, 0.5f, 0f, 0f, -30f)]
        [TestCase(0.866f, 0.866f, 0.5f, 0.5f, 0f, 0f)]
        [TestCase(-0.866f, -0.866f, 0.5f, 0.5f, 0f, 0f)]
        [TestCase(0.866f, 0.866f, 1f, 0f, 30f, -30f)]
        [TestCase(0.866f, 0.866f, 1f, 1f, 30f, 30f)]
        public void InterpolateRotationTest(float dotLimitX, float dotLimitY, float lerpValueX, float lerpValueY, float resultRotationDegreesX, float resultRotationDegreesY)
        {
            quaternion result = MathExtensions.GetLimitedNormalizedRotation(new float2(lerpValueX, lerpValueY), new float2(dotLimitX, dotLimitY));
            var degreesEuler = math.degrees(math.Euler(result));
            TestContext.WriteLine($"{result} -> {degreesEuler}");
            Assert.AreEqual(resultRotationDegreesX, degreesEuler.x, Epsilon,  "x degrees not match");
            Assert.AreEqual(resultRotationDegreesY, degreesEuler.y, Epsilon, "y degrees not match");
        }
    }

}
