using ZE.Utils;

namespace ZE.MechBattle.Editor.Tests
{
    // generated by Google AI

    using NUnit.Framework;
    using Unity.Mathematics;

    public class RotationClamp2DTests
    {
        private const float Epsilon = 0.0001f;

        #region Тесты для GetAxisProjectionsFast2D

        [Test]
        public void GetAxisProjections2D_Identity_ReturnsOnes()
        {
            // Без вращения локальные оси соосны мировым (косинус = 1)
            quaternion q = quaternion.identity;
            float2 dots = MathExtensions.GetAxisProjectionsFast2D(q);

            Assert.AreEqual(1f, dots.x, Epsilon);
            Assert.AreEqual(1f, dots.y, Epsilon);
        }

        [Test]
        public void GetAxisProjections2D_Rotate90AroundY_FlipsX()
        {
            // Поворот на 90 градусов вокруг Y смещает ось X. Ось Y остается на месте.
            quaternion q = quaternion.AxisAngle(new float3(0, 1, 0), math.radians(90f));
            float2 dots = MathExtensions.GetAxisProjectionsFast2D(q);

            Assert.AreEqual(0f, dots.x, Epsilon, "Ось X должна повернуться на 90 градусов (cos = 0)");
            Assert.AreEqual(1f, dots.y, Epsilon, "Ось Y не должна измениться (cos = 1)");
        }

        [Test]
        public void GetAxisProjections2D_Rotate180AroundX_InvertsY()
        {
            // Поворот на 180 градусов вокруг X. Локальная Y смотрит строго вниз.
            quaternion q = quaternion.AxisAngle(new float3(1, 0, 0), math.radians(180f));
            float2 dots = MathExtensions.GetAxisProjectionsFast2D(q);

            Assert.AreEqual(1f, dots.x, Epsilon, "Ось X на месте (cos = 1)");
            Assert.AreEqual(-1f, dots.y, Epsilon, "Ось Y перевернута (cos = -1)");
        }

        #endregion

        #region Тесты для ClampRotation

        [Test]
        public void ClampRotation_WithinLimits_ReturnsSameRotation()
        {
            // Небольшой поворот на 15 градусов вокруг X
            quaternion initialRot = quaternion.AxisAngle(new float3(1, 0, 0), math.radians(15f));

            // Лимит — косинус 45 градусов (примерно 0.7071)
            float maxCos = math.cos(math.radians(45f));
            float2 limits = new float2(maxCos, maxCos);

            quaternion clampedRot = MathExtensions.ClampRotation(initialRot, limits);

            // Поворот не должен быть изменен, так как 15° < 45°
            Assert.AreEqual(initialRot.value.x, clampedRot.value.x, Epsilon);
            Assert.AreEqual(initialRot.value.y, clampedRot.value.y, Epsilon);
            Assert.AreEqual(initialRot.value.z, clampedRot.value.z, Epsilon);
            Assert.AreEqual(initialRot.value.w, clampedRot.value.w, Epsilon);
        }

        [Test]
        public void ClampRotation_ExceedsXLimit_ClampsToBoundary()
        {
            // Поворот на 60 градусов вокруг Y (отклоняет ось X сильнее лимита)
            quaternion excessiveRot = quaternion.AxisAngle(new float3(0, 1, 0), math.radians(60f));

            // Лимит — 45 градусов (косинус 45° = 0.7071f)
            float maxAllowedCos = math.cos(math.radians(45f));
            float2 limits = new float2(maxAllowedCos, maxAllowedCos);

            quaternion clampedRot = MathExtensions.ClampRotation(excessiveRot, limits);

            // Проверяем проекции зажатого кватерниона
            float2 finalDots = MathExtensions.GetAxisProjectionsFast2D(clampedRot);

            // Теперь тест успешно проходит: отклонение по X зажато ровно на косинусе 45 градусов
            Assert.AreEqual(maxAllowedCos, finalDots.x, Epsilon);
        }

        #endregion
    }


}
