using ZE.Utils;

namespace ZE.MechBattle.Editor.Tests
{
    // generated by Google AI

    using NUnit.Framework;
    using Unity.Mathematics;

    public class RotationClamp2DTests
    {
        private const float Epsilon = 0.0001f;

        #region Тесты для GetAxisProjectionsFast2D

        [Test]
        public void GetAxisProjections2D_Identity_ReturnsOnes()
        {
            // Без вращения локальные оси соосны мировым (косинус = 1)
            quaternion q = quaternion.identity;
            float2 dots = MathExtensions.GetAxisProjectionsFast2D(q);

            Assert.AreEqual(1f, dots.x, Epsilon);
            Assert.AreEqual(1f, dots.y, Epsilon);
        }

        [Test]
        public void GetAxisProjections2D_Rotate90AroundY_FlipsX()
        {
            // Поворот на 90 градусов вокруг Y смещает ось X. Ось Y остается на месте.
            quaternion q = quaternion.AxisAngle(new float3(0, 1, 0), math.radians(90f));
            float2 dots = MathExtensions.GetAxisProjectionsFast2D(q);

            Assert.AreEqual(0f, dots.x, Epsilon, "Ось X должна повернуться на 90 градусов (cos = 0)");
            Assert.AreEqual(1f, dots.y, Epsilon, "Ось Y не должна измениться (cos = 1)");
        }

        [Test]
        public void GetAxisProjections2D_Rotate180AroundX_InvertsY()
        {
            // Поворот на 180 градусов вокруг X. Локальная Y смотрит строго вниз.
            quaternion q = quaternion.AxisAngle(new float3(1, 0, 0), math.radians(180f));
            float2 dots = MathExtensions.GetAxisProjectionsFast2D(q);

            Assert.AreEqual(1f, dots.x, Epsilon, "Ось X на месте (cos = 1)");
            Assert.AreEqual(-1f, dots.y, Epsilon, "Ось Y перевернута (cos = -1)");
        }

        #endregion

        #region Тесты для ClampRotation

        [Test]
        public void ClampRotation_ExceedsUpDownLimit_ClampsXLimit()
        {
            // Вращаем вокруг оси X на 60 градусов (наклон вверх-вниз)
            quaternion excessiveRot = quaternion.AxisAngle(new float3(1, 0, 0), math.radians(60f));

            // Лимит: X (вверх-вниз) = 45°, Y (влево-вправо) = Безлимитный
            float maxAllowedCos = math.cos(math.radians(45f));
            float2 limits = new float2(maxAllowedCos, -1f);

            quaternion clampedRot = MathExtensions.ClampRotation(excessiveRot, limits);

            // Проверяем итоговую проекцию оси Up (rawDots.y) через метод
            float2 rawDots = MathExtensions.GetAxisProjectionsFast2D(clampedRot);

            // Так как limits.x управляет наклоном вверх-вниз, именно проекция оси Up должна зажаться на 45°
            Assert.AreEqual(maxAllowedCos, rawDots.y, Epsilon, "Наклон вверх-вниз (ось Up) не зажался корректно!");
        }

        [Test]
        public void ClampRotation_ExceedsLeftRightLimit_ClampsYLimit()
        {
            // Вращаем вокруг оси Y на 60 градусов (поворот влево-вправо)
            quaternion excessiveRot = quaternion.AxisAngle(new float3(0, 1, 0), math.radians(60f));

            // Лимит: X (вверх-вниз) = Безлимитный, Y (влево-вправо) = 45°
            float maxAllowedCos = math.cos(math.radians(45f));
            float2 limits = new float2(-1f, maxAllowedCos);

            quaternion clampedRot = MathExtensions.ClampRotation(excessiveRot, limits);

            // Проверяем итоговую проекцию оси Right (rawDots.x)
            float2 rawDots = MathExtensions.GetAxisProjectionsFast2D(clampedRot);

            // Так как limits.y управляет влево-вправо, зажаться должна проекция оси Right
            Assert.AreEqual(maxAllowedCos, rawDots.x, Epsilon, "Поворот влево-вправо (ось Right) не зажался корректно!");
        }

        #endregion
    }


}
