using System.Runtime.CompilerServices;
using Unity.Mathematics;

namespace ZE.MechBattle.Navigation
{
   

    // generated by Google AI based on all logic versions
    public readonly struct UniversalEdgeLimitLogic
    {
        private readonly int3 _minLimits;
        private readonly int3 _maxLimits;
        private readonly int _axisP, _axisS1, _axisS2;

        public UniversalEdgeLimitLogic(HexEdge edge, IntTriangularPos center, int radius)
        {
            var limits = edge.GetEdgeTriangleLimits(center, radius);
            _minLimits = limits.min;
            _maxLimits = limits.max;

            switch (edge)
            {
                case HexEdge.Top:
                case HexEdge.Bottom:
                    _axisP = 1; _axisS1 = 0; _axisS2 = 2; break;
                case HexEdge.TopRight:
                case HexEdge.BottomLeft:
                    _axisP = 0; _axisS1 = 1; _axisS2 = 2; break;
                default: // BottomRight, TopLeft
                    _axisP = 2; _axisS1 = 0; _axisS2 = 1; break;
            }
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public bool IsEdgeTriangle(IntTriangularPos pos)
        {
            int3 p = pos.ToInt3();

            bool sideChecks = p[_axisS1] >= _minLimits[_axisS1] & p[_axisS1] <= _maxLimits[_axisS1] &
                              p[_axisS2] >= _minLimits[_axisS2] & p[_axisS2] <= _maxLimits[_axisS2];

            int pVal = p[_axisP];
            bool pCheck = pos.IsPeak ? (pVal == _minLimits[_axisP]) : (pVal == _maxLimits[_axisP]);

            return pCheck & sideChecks;
        }
    }

    //public interface IEdgeLimitLogic
    //{
    //    bool IsEdgeTriangle(IntTriangularPos pos);
    //}

    //public readonly struct TopEdgeLimitLogic : IEdgeLimitLogic
    //{
    //    private readonly IntTriangularPos _hexCenter;
    //    private readonly int _radius;
    //    private readonly int3 _minLimits;
    //    private readonly int3 _maxLimits;

    //    public TopEdgeLimitLogic(IntTriangularPos center, int radius)
    //    {
    //        _hexCenter = center;
    //        _radius = radius;

    //        var limits = HexEdge.Top.GetEdgeTriangleLimits(_hexCenter, _radius);
    //        _minLimits = limits.min;
    //        _maxLimits = limits.max;
    //    }

    //    public bool IsEdgeTriangle(IntTriangularPos pos)
    //    {
    //        var sideChecks = math.all(pos.XZ >= _minLimits.xz & pos.XZ <= _maxLimits.xz);
    //        var ycheck = pos.IsPeak ? (pos.Y == _minLimits.y) : (pos.Y == _maxLimits.y);
    //        return ycheck & sideChecks;
    //    }
    //}

    //public readonly struct TopRightEdgeLimitLogic : IEdgeLimitLogic
    //{
    //    private readonly IntTriangularPos _hexCenter;
    //    private readonly int _radius;
    //    private readonly int3 _minLimits;
    //    private readonly int3 _maxLimits;

    //    public TopRightEdgeLimitLogic(IntTriangularPos center, int radius)
    //    {
    //        _hexCenter = center;
    //        _radius = radius;

    //        var limits = HexEdge.TopRight.GetEdgeTriangleLimits(_hexCenter, _radius);
    //        _minLimits = limits.min;
    //        _maxLimits = limits.max;
    //    }

    //    public bool IsEdgeTriangle(IntTriangularPos pos)
    //    {
    //        var sideChecks = math.all(pos.YZ >= _minLimits.yz & pos.YZ <= _maxLimits.yz);
    //        var xcheck = pos.IsPeak ? (pos.X == _minLimits.x) : (pos.X == _maxLimits.x) ;
    //        return xcheck & sideChecks;
    //    }
    //}

    //public readonly struct BottomRightEdgeLimitLogic : IEdgeLimitLogic
    //{
    //    private readonly IntTriangularPos _hexCenter;
    //    private readonly int _radius;
    //    private readonly int3 _minLimits;
    //    private readonly int3 _maxLimits;

    //    public BottomRightEdgeLimitLogic(IntTriangularPos center, int radius)
    //    {
    //        _hexCenter = center;
    //        _radius = radius;

    //        var limits = HexEdge.BottomRight.GetEdgeTriangleLimits(_hexCenter, _radius);
    //        _minLimits = limits.min;
    //        _maxLimits = limits.max;
    //    }

    //    public bool IsEdgeTriangle(IntTriangularPos pos)
    //    {
    //        var sideChecks = math.all(pos.XY >= _minLimits.xy & pos.XY <= _maxLimits.xy);
    //        var zcheck = pos.IsPeak ? (pos.Z == _minLimits.z) : (pos.Z == _maxLimits.z);
    //        return zcheck & sideChecks;
    //    }
    //}

    //public readonly struct BottomEdgeLimitLogic : IEdgeLimitLogic
    //{
    //    private readonly IntTriangularPos _hexCenter;
    //    private readonly int _radius;
    //    private readonly int3 _minLimits;
    //    private readonly int3 _maxLimits;

    //    public BottomEdgeLimitLogic(IntTriangularPos center, int radius)
    //    {
    //        _hexCenter = center;
    //        _radius = radius;

    //        var limits = HexEdge.Bottom.GetEdgeTriangleLimits(_hexCenter, _radius);
    //        _minLimits = limits.min;
    //        _maxLimits = limits.max;
    //    }

    //    public bool IsEdgeTriangle(IntTriangularPos pos)
    //    {
    //        var sideChecks = math.all(pos.XZ >= _minLimits.xz & pos.XZ <= _maxLimits.xz);
    //        var ycheck = pos.IsPeak ? (pos.Y == _minLimits.y) : (pos.Y == _maxLimits.y);
    //        return ycheck & sideChecks;
    //    }
    //}

    //public readonly struct BottomLeftEdgeLimitLogic : IEdgeLimitLogic
    //{
    //    private readonly IntTriangularPos _hexCenter;
    //    private readonly int _radius;
    //    private readonly int3 _minLimits;
    //    private readonly int3 _maxLimits;

    //    public BottomLeftEdgeLimitLogic(IntTriangularPos center, int radius)
    //    {
    //        _hexCenter = center;
    //        _radius = radius;

    //        var limits = HexEdge.BottomLeft.GetEdgeTriangleLimits(_hexCenter, _radius);
    //        _minLimits = limits.min;
    //        _maxLimits = limits.max;
    //    }

    //    public bool IsEdgeTriangle(IntTriangularPos pos)
    //    {
    //        var sideChecks = math.all(pos.YZ >= _minLimits.yz & pos.YZ <= _maxLimits.yz);
    //        var xcheck = pos.IsPeak ? (pos.X == _minLimits.x) : (pos.X == _maxLimits.x) ;
    //        return xcheck & sideChecks;
    //    }
    //}

    //public readonly struct TopLeftEdgeLimitLogic : IEdgeLimitLogic
    //{
    //    private readonly IntTriangularPos _hexCenter;
    //    private readonly int _radius;
    //    private readonly int3 _minLimits;
    //    private readonly int3 _maxLimits;

    //    public TopLeftEdgeLimitLogic(IntTriangularPos center, int radius)
    //    {
    //        _hexCenter = center;
    //        _radius = radius;

    //        var limits = HexEdge.TopLeft.GetEdgeTriangleLimits(_hexCenter, _radius);
    //        _minLimits = limits.min;
    //        _maxLimits = limits.max;
    //    }

    //    public bool IsEdgeTriangle(IntTriangularPos pos)
    //    {
    //        var sideChecks = math.all(pos.XY >= _minLimits.xy & pos.XY <= _maxLimits.xy);
    //        var zcheck = pos.IsPeak ? (pos.Z == _minLimits.z) : (pos.Z == _maxLimits.z);
    //        return zcheck & sideChecks;
    //    }
    //}
}
