using UnityEngine;
using UnityEditor;
using UnityEditor.AddressableAssets;
using UnityEditor.AddressableAssets.Settings;
using ZE.UiService;

// generated by Google AI

[InitializeOnLoad]
public static class AddressableWindowNameInitializer
{
    static AddressableWindowNameInitializer()
    {
        AddressableAssetSettingsDefaultObject.Settings.OnModification += OnAddressablesModified;
    }

    private static void OnAddressablesModified(AddressableAssetSettings settings, AddressableAssetSettings.ModificationEvent modificationEvent, object data)
    {
        if (modificationEvent != AddressableAssetSettings.ModificationEvent.EntryAdded) return;

        if (data is AddressableAssetEntry entry)
        {
            ProcessEntry(entry);
        }
        else if (data is System.Collections.IEnumerable enumerable)
        {
            foreach (var item in enumerable)
            {
                if (item is AddressableAssetEntry e) ProcessEntry(e);
            }
        }
    }

    private static void ProcessEntry(AddressableAssetEntry entry)
    {
        string path = entry.AssetPath;

        GameObject prefab = AssetDatabase.LoadAssetAtPath<GameObject>(path);
        if (prefab == null) return;

        if (!prefab.TryGetComponent<UiWindow>(out var windowComponent)) return;
        string fileName = System.IO.Path.GetFileNameWithoutExtension(path);
        string snakeCaseAddress = windowComponent.GetWindowDefaultAssetName();
        entry.SetAddress(snakeCaseAddress);

        Debug.Log($"[Addressables] Window {windowComponent.GetType().Name} new asset address set: {snakeCaseAddress}");
    }
}

