using System.Globalization;
using UnityEditor;
using UnityEngine;
using ZE.MechBattle;
using Unity.Mathematics;

public class ColliderSetupDataCopy
{
    // generated by Deepseek


    [MenuItem("CONTEXT/BoxCollider/Copy ColliderSetupInfo")]
    private static void CopyBoxColliderData(MenuCommand command)
    {
        BoxCollider boxCollider = command.context as BoxCollider;
        if (boxCollider == null) return;

        var colliderSetupData = new ColliderSetupInfo(boxCollider);
        InsertAsSerializedField(colliderSetupData);
        Debug.Log($"Collider setup data copied");
    }

    [MenuItem("CONTEXT/SphereCollider/Copy ColliderSetupInfo")]
    private static void CopySphereColliderData(MenuCommand command)
    {
        SphereCollider sphereCollider = command.context as SphereCollider;
        if (sphereCollider == null) return;

        var colliderSetupData = new ColliderSetupInfo(sphereCollider);
        InsertAsSerializedField(colliderSetupData);

        Debug.Log($"Collider setup data copied");
    }

    // other way is to create monobehaviour object with serialized field, and get generic json from it
    // generated by Google AI
    private static void InsertAsSerializedField(ColliderSetupInfo info)
    {
        string f(float val) => val.ToString(CultureInfo.InvariantCulture);
        var pos = info.LocalPosition;
        var rot = info.LocalRotation.value;
        var size = info.Size;

        string json = "{" +
            "\"name\":\"data\"," +
            "\"type\":-1," +
            "\"children\":[" +
                $"{{\"name\":\"ColliderType\",\"type\":7,\"val\":\"Enum:{info.ColliderType}\"}}," +
                $"{{\"name\":\"LocalPosition\",\"type\":-1,\"children\":[" +
                    $"{{\"name\":\"x\",\"type\":2,\"val\":{f(pos.x)}}}," +
                    $"{{\"name\":\"y\",\"type\":2,\"val\":{f(pos.y)}}}," +
                    $"{{\"name\":\"z\",\"type\":2,\"val\":{f(pos.z)}}}" +
                $"]}}," +
                $"{{\"name\":\"LocalRotation\",\"type\":-1,\"children\":[" +
                    $"{{\"name\":\"value\",\"type\":-1,\"children\":[" +
                        $"{{\"name\":\"x\",\"type\":2,\"val\":{f(rot.x)}}}," +
                        $"{{\"name\":\"y\",\"type\":2,\"val\":{f(rot.y)}}}," +
                        $"{{\"name\":\"z\",\"type\":2,\"val\":{f(rot.z)}}}," +
                        $"{{\"name\":\"w\",\"type\":2,\"val\":{f(rot.w)}}}" +
                    $"]}}" +
                $"]}}," +
                $"{{\"name\":\"Size\",\"type\":-1,\"children\":[" +
                    $"{{\"name\":\"x\",\"type\":2,\"val\":{f(size.x)}}}," +
                    $"{{\"name\":\"y\",\"type\":2,\"val\":{f(size.y)}}}," +
                    $"{{\"name\":\"z\",\"type\":2,\"val\":{f(size.z)}}}" +
                $"]}}" +
            "]" +
        "}";

        EditorGUIUtility.systemCopyBuffer = $"GenericPropertyJSON:{json}";
    }
}
