using System.Collections;
using System.Collections.Generic;
using Unity.Burst;
using Unity.Mathematics;

namespace ZE.MechBattle.Navigation
{
    // generated by Google AI
    public interface IEdgeEnumerationLogic
    {
        bool StartsWithPeak { get; }
        IntTriangularPos GetStart(int trianglesPerEdge, NavigationHexPosition hex);
        IntTriangularPos EvenStep(IntTriangularPos pos);
        IntTriangularPos OddStep(IntTriangularPos pos);
    }

    [BurstCompile]
    public struct EdgeEnumerator<T> : IEnumerator<IntTriangularPos>, IEnumerable<IntTriangularPos> where T : struct, IEdgeEnumerationLogic
    {
        private T _logic;
        private int _limit;
        private int _step;
        private int _subStep;
        private IntTriangularPos _pos;

        public EdgeEnumerator(int trianglesPerEdge, NavigationHexPosition hex)
        {
            _logic = default; 
            _limit = trianglesPerEdge;
            _pos = _logic.GetStart(trianglesPerEdge, hex);
            _step = 0;
            _subStep = 0;
        }

        public EdgeEnumerator(NavigationPortalExit exit)
        {
            _logic = default;
            _limit = exit.Length;
            _pos = exit.StartTriangle;

            _step = 0;
            _subStep = _logic.StartsWithPeak == _pos.IsPeak ? 0 : 1;            
        }

        public bool MoveNext()
        {
            if (_step == -1)
            {
                _step = 0;
                return true;
            }
            if (_step == 0)
            {
                _step++;
                _subStep = 0;
                return true;
            }

            if (_step < _limit)
            {
                switch (_subStep)
                {
                    case 0: 
                        _pos = _logic.EvenStep(_pos);
                        _subStep = 1;
                        return true;

                    case 1: 
                        _pos = _logic.OddStep(_pos);
                        _subStep = 0;
                        _step++;
                        return true;
                }
            }
            return false;
        }

        public IntTriangularPos Current => _pos;
        object IEnumerator.Current => Current;
        public EdgeEnumerator<T> GetEnumerator() => this;
        public void Dispose() { }
        public void Reset() { }

        IEnumerator<IntTriangularPos> IEnumerable<IntTriangularPos>.GetEnumerator() => GetEnumerator();
        IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();
    }


    public struct TopEdgeEnumerationLogic : IEdgeEnumerationLogic
    {
        // Top left corner -> top right
        public bool StartsWithPeak => false;
        public const PeakNeighbour PeakDirection = PeakNeighbour.EdgeUpRight;
        public const ValleyNeighbour ValleyDirection = ValleyNeighbour.EdgeDownRight;

        public IntTriangularPos GetStart(int trianglesPerEdge, NavigationHexPosition hex)
        {
            return hex.TriangularCenterPos + new int3(0, trianglesPerEdge,- trianglesPerEdge + 1);            
        }
        public IntTriangularPos EvenStep(IntTriangularPos pos) => TriangularMath.GetValleyNeighbour(pos, ValleyDirection);
        public IntTriangularPos OddStep(IntTriangularPos pos) => TriangularMath.GetPeakNeighbour(pos, PeakDirection);

        public static IntTriangularPos AlongsidePeakVector => PeakDirection.ToTriangularOffsetVector();
        public static IntTriangularPos AlongsideValleyVector => ValleyDirection.ToTriangularOffsetVector();
    }

    public struct TopRightEdgeEnumerationLogic : IEdgeEnumerationLogic
    {
        // Top right corner -> right corner
        public bool StartsWithPeak => true;
        public const PeakNeighbour PeakDirection = PeakNeighbour.EdgeDown;
        public const ValleyNeighbour ValleyDirection = ValleyNeighbour.EdgeDownRight;

        public IntTriangularPos GetStart(int trianglesPerEdge, NavigationHexPosition hex)
        {
            return hex.TriangularCenterPos + new int3(-trianglesPerEdge, trianglesPerEdge - 1, 0);
        }
        public IntTriangularPos OddStep(IntTriangularPos pos) => TriangularMath.GetValleyNeighbour(pos, ValleyDirection);
        public IntTriangularPos EvenStep(IntTriangularPos pos) => TriangularMath.GetPeakNeighbour(pos, PeakDirection);

        public static IntTriangularPos AlongsidePeakVector => PeakDirection.ToTriangularOffsetVector();
        public static IntTriangularPos AlongsideValleyVector => ValleyDirection.ToTriangularOffsetVector();
    }

    public struct BottomRightEdgeEnumerationLogic : IEdgeEnumerationLogic
    {
        // right corner -> bottom right corner
        public bool StartsWithPeak => false;
        public const PeakNeighbour PeakDirection = PeakNeighbour.EdgeDown;
        public const ValleyNeighbour ValleyDirection = ValleyNeighbour.EdgeDownLeft;

        public IntTriangularPos GetStart(int trianglesPerEdge, NavigationHexPosition hex)
        {
            return hex.TriangularCenterPos + new int3(-trianglesPerEdge + 1, 0, trianglesPerEdge);
        }
        public IntTriangularPos OddStep(IntTriangularPos pos) => TriangularMath.GetPeakNeighbour(pos, PeakDirection);
        public IntTriangularPos EvenStep(IntTriangularPos pos) => TriangularMath.GetValleyNeighbour(pos, ValleyDirection);

        public static IntTriangularPos AlongsidePeakVector => PeakDirection.ToTriangularOffsetVector();
        public static IntTriangularPos AlongsideValleyVector => ValleyDirection.ToTriangularOffsetVector();
    }

    public struct BottomEdgeEnumerationLogic : IEdgeEnumerationLogic
    {
        // bottom left corner -> bottom right corner
        public bool StartsWithPeak => true;
        public const PeakNeighbour PeakDirection = PeakNeighbour.EdgeUpRight;
        public const ValleyNeighbour ValleyDirection = ValleyNeighbour.EdgeDownRight;

        public IntTriangularPos GetStart(int trianglesPerEdge, NavigationHexPosition hex)
        {
            return hex.TriangularCenterPos + new int3(trianglesPerEdge - 1, -trianglesPerEdge, 0);
        }
        public IntTriangularPos EvenStep(IntTriangularPos pos) => TriangularMath.GetPeakNeighbour(pos, PeakNeighbour.EdgeUpRight);
        public IntTriangularPos OddStep(IntTriangularPos pos) => TriangularMath.GetValleyNeighbour(pos, ValleyNeighbour.EdgeDownRight);

        public static IntTriangularPos AlongsidePeakVector => PeakDirection.ToTriangularOffsetVector();
        public static IntTriangularPos AlongsideValleyVector => ValleyDirection.ToTriangularOffsetVector();
    }

    public struct BottomLeftEdgeEnumerationLogic : IEdgeEnumerationLogic
    {
        // left corner -> bottom left corner
        public bool StartsWithPeak => false;
        public const PeakNeighbour PeakDirection = PeakNeighbour.EdgeDown;
        public const ValleyNeighbour ValleyDirection = ValleyNeighbour.EdgeDownRight;

        public IntTriangularPos GetStart(int trianglesPerEdge, NavigationHexPosition hex)
        {
            return hex.TriangularCenterPos + new int3(trianglesPerEdge, 0, -trianglesPerEdge + 1);
        }
        public IntTriangularPos OddStep(IntTriangularPos pos) => TriangularMath.GetPeakNeighbour(pos, PeakNeighbour.EdgeDown);
        public IntTriangularPos EvenStep(IntTriangularPos pos) => TriangularMath.GetValleyNeighbour(pos, ValleyNeighbour.EdgeDownRight);

        public static IntTriangularPos AlongsidePeakVector => PeakDirection.ToTriangularOffsetVector();
        public static IntTriangularPos AlongsideValleyVector => ValleyDirection.ToTriangularOffsetVector();
    }

    public struct TopLeftEdgeEnumerationLogic : IEdgeEnumerationLogic
    {
        // left corner -> top left corner
        public bool StartsWithPeak => true;
        public const PeakNeighbour PeakDirection = PeakNeighbour.EdgeUpRight;
        public const ValleyNeighbour ValleyDirection = ValleyNeighbour.EdgeUp;

        public IntTriangularPos GetStart(int trianglesPerEdge, NavigationHexPosition hex)
        {
            return hex.TriangularCenterPos + new int3(trianglesPerEdge-1, 0, -trianglesPerEdge);
        }
        public IntTriangularPos EvenStep(IntTriangularPos pos) => TriangularMath.GetPeakNeighbour(pos, PeakNeighbour.EdgeUpRight);
        public IntTriangularPos OddStep(IntTriangularPos pos) => TriangularMath.GetValleyNeighbour(pos, ValleyNeighbour.EdgeUp);

        public static IntTriangularPos AlongsidePeakVector => PeakDirection.ToTriangularOffsetVector();
        public static IntTriangularPos AlongsideValleyVector => ValleyDirection.ToTriangularOffsetVector();
    }
}
