using NUnit.Framework;
using Unity.Mathematics;

namespace ZE.MechBattle.Navigation.Tests
{
    // generated by Google AI
    public class HexEdgeToOffsetConversionTest
    {
        private static readonly (HexEdge edge, int2 expected)[] TestCases = new[]
        {
        (HexEdge.Top,         new int2(0, 1)),
        (HexEdge.TopRight,    new int2(1, 0)),
        (HexEdge.BottomRight, new int2(1, -1)),
        (HexEdge.Bottom,      new int2(0, -1)),
        (HexEdge.BottomLeft,  new int2(-1, 0)),
        (HexEdge.TopLeft,     new int2(-1, 1))
        };

        [Test]
        public void ToHexOffsetVector_AllEdges_ReturnsCorrectVectors()
        {
            foreach (var (edge, expected) in TestCases)
            {
                int2 result = edge.ToHexOffsetVector();
                Assert.AreEqual(expected, result, $"ToHexOffsetVector incorrect for {edge}");
            }
        }

        [Test]
        public void ToHexEdge_AllVectors_ReturnsCorrectEdges()
        {
            foreach (var (expectedEdge, vector) in TestCases)
            {
                HexEdge result = vector.ToHexEdge();
                Assert.AreEqual(expectedEdge, result, $"ToHexEdge incorrect for {vector}");
            }
        }

        [Test]
        public void Bidirectional_Consistency_Test()
        {
            for (int i = 0; i < 6; i++)
            {
                HexEdge original = (HexEdge)i;
                HexEdge processed = original.ToHexOffsetVector().ToHexEdge();

                Assert.AreEqual(original, processed, $"Double convertation failed {original}");
            }
        }
    }

}
