using Scellecs.Morpeh;
using Unity.Mathematics;
using Unity.IL2CPP.CompilerServices;
using VContainer;
using ZE.Utils;

namespace ZE.MechBattle.Ecs {
    [Il2CppSetOption(Option.NullChecks, false)]
    [Il2CppSetOption(Option.ArrayBoundsChecks, false)]
    [Il2CppSetOption(Option.DivideByZeroChecks, false)]
    public sealed class WeaponAimCalculationSystem : PausableSystem 
    {
        private Filter _aimingTowerWeaponsFilter;
        private Filter _aimingbarrelWeaponsFilter;
        private Filter _idleTowerWeaponsFilter;
        private Filter _idlebarrelWeaponsFilter;

        private Stash<AttackTargetComponent> _attackTargetComponent;
        private Stash<PositionComponent> _positions;
        private Stash<RotationComponent> _rotations;
        private Stash<WeaponTowerAimTargetComponent> _towerAims;
        private Stash<WeaponBarrelAimTargetComponent> _barrelAims;
        private Stash<WeaponTowerComponent> _weaponTowers;
        private Stash<WeaponBarrelComponent> _weaponbarrels;
        private readonly TransformAspectHandler _transformAspectHandler;

        [Inject]
        public WeaponAimCalculationSystem(TransformAspectHandler transformAspectHandler, SceneFlagsManager sceneFlagsManager) : base(sceneFlagsManager) 
        {
            _transformAspectHandler = transformAspectHandler;
        }

        public override void OnAwake() 
        {
            _aimingTowerWeaponsFilter = World.Filter
                .With<WeaponTowerComponent>()
                .With<AttackTargetComponent>()
                .Build();
            _aimingbarrelWeaponsFilter = World.Filter
                .With<WeaponBarrelComponent>()
                .With<AttackTargetComponent>()
                .Build();

            _idleTowerWeaponsFilter = World.Filter
                .With<WeaponTowerStowTag>()
                .Without<AttackTargetComponent>().Build();
            _idlebarrelWeaponsFilter = World.Filter
                .With<WeaponBarrelStowTag>()
                .Without<AttackTargetComponent>().Build();

            _attackTargetComponent = World.GetStash<AttackTargetComponent>();   
            _positions = World.GetStash<PositionComponent>();
            _rotations = World.GetStash<RotationComponent>();
            _towerAims = World.GetStash<WeaponTowerAimTargetComponent>();
            _barrelAims = World.GetStash<WeaponBarrelAimTargetComponent>();

            _weaponTowers = World.GetStash<WeaponTowerComponent>();
            _weaponbarrels = World.GetStash<WeaponBarrelComponent>();
        }

        public override void OnUpdate(float deltaTime) 
        {
            if (IsPaused) return;

            foreach (var weaponEntity in _aimingTowerWeaponsFilter)
            {
                var targetEntity = _attackTargetComponent.Get(weaponEntity).Entity;
                var targetPos = _positions.Get(targetEntity).Value;
                
                var weaponLafetPos = _positions.Get(weaponEntity).Value;
                var normalizedTargetDir = math.normalize(targetPos - weaponLafetPos);

                _towerAims.Set(weaponEntity, new() { RadianValue = GetYaw(normalizedTargetDir)});
            }

            foreach (var weaponEntity in _aimingbarrelWeaponsFilter)
            {
                var targetEntity = _attackTargetComponent.Get(weaponEntity).Entity;
                var targetPos = _positions.Get(targetEntity).Value;

                var weaponLafetPos = _positions.Get(weaponEntity).Value;
                var targetDir = targetPos - weaponLafetPos;
                var barrelComponent = _weaponbarrels.Get(weaponEntity);

                if (!barrelComponent.YRotationPossible)
                {
                    // only up\down
                    var pitch = GetPitch(math.normalize(targetDir));
                    _barrelAims.Set(weaponEntity, new() { RadianValueV2 = new float2(pitch, 0f) });
                }
                else
                {
                    //full aim
                    var pitchYaw = GetPitchYawRotation(targetDir);
                    _barrelAims.Set(weaponEntity, new() { RadianValueV2 = pitchYaw });
                }
            }



            foreach (var weaponEntity in _idleTowerWeaponsFilter)
            {
                _weaponTowers.Get(weaponEntity).RotationRadianValue = 0f;
            }

            foreach (var weaponEntity in _idlebarrelWeaponsFilter)
            {
                _weaponbarrels.Get(weaponEntity).RadianRotation = float2.zero;
            }
        }



        // generated by GoogleAI
        private float2 GetPitchYawRotation(float3 targetDir)
        {
            float3 normalizedDir = math.normalize(targetDir);            
            return new float2(GetPitch(normalizedDir), GetYaw(normalizedDir));
        }

        private float GetPitch(float3 normalizedDir)
        {
            float xzLength = math.sqrt(normalizedDir.x * normalizedDir.x + normalizedDir.z * normalizedDir.z);
            return math.atan2(normalizedDir.y, xzLength);            
        }

        private float GetYaw(float3 normalizedDir)
        {
            return math.atan2(normalizedDir.x, normalizedDir.z);
        }
    }
}