using NUnit.Framework;
using Unity.Mathematics;
using System.Collections.Generic;

namespace ZE.MechBattle.Navigation.Tests
{
    // generated by Google AI
    public class HexRadiusTests
    {
        [Test]
        [TestCase(0, 1)]      
        [TestCase(1, 7)]      
        [TestCase(2, 19)]     
        [TestCase(5, 91)] 
        public void Enumerator_ReturnsCorrectAmountOfHexes(int radius, int expectedCount)
        {
            var center = new int2(10, 10);
            var enumerator = new HexRadiusEnumerator(center, radius);

            int count = 0;
            foreach (var hex in enumerator)
            {
                count++;
            }

            Assert.AreEqual(expectedCount, count, $"Hexes count with radius of {radius} doesn't match ");
        }

        [Test]
        public void Enumerator_AllHexesWithinRange()
        {
            int2 center = new int2(0, 0);
            int radius = 3;
            var enumerator = new HexRadiusEnumerator(center, radius);

            foreach (var hex in enumerator)
            {
                int distance = HexMath.CalculateHexPosDistance(center, hex);
                Assert.LessOrEqual(distance, radius, $"Hex {hex} is out of radius {radius}. Distance: {distance}");
            }
        }

        [Test]
        public void Enumerator_NoDuplicates()
        {
            int2 center = new int2(5, -5);
            int radius = 4;
            var results = new HashSet<int2>();
            var enumerator = new HexRadiusEnumerator(center, radius);

            foreach (var hex in enumerator)
            {
                Assert.IsTrue(results.Add(hex), $"Hex duplicate found: {hex}");
            }
        }

        [Test]
        public void CalculateMinHexRadius_InverseCheck()
        {
            for (int N = 1; N <= 100; N++)
            {
                int exactCount = 6 * N * N;
                int overflowCount = exactCount + 1;

                Assert.AreEqual(N, HexMath.GetMinHexRadius(exactCount),
                    $"Failed for exact count of radius {N}");

                Assert.AreEqual(N + 1, HexMath.GetMinHexRadius(overflowCount),
                    $"Failed for overflow count of radius {N}");
            }
        }
    }

}
