using R3;
using System;
using System.Threading;
using UnityEditor;
using UnityEngine;

namespace ZE.MechBattle.Navigation.DebugOverlay
{
    public class PathDrawingSession : IDisposable
    {
        public bool IsDisposed { get; private set; }
        public CancellationToken CancellationToken => _cancellationTokenSource.Token;

        private ReactiveProperty<bool> _isAsyncOperationInProgressProperty;
        private CompositeDisposable _compositeDisposable;
        private CancellationTokenSource _cancellationTokenSource;

        public PathDrawingSession(Action onEditorUpdate)
        {
            _isAsyncOperationInProgressProperty = new(false);
            _compositeDisposable = new();
            _cancellationTokenSource = new();

            // generated by Google AI
            var editorUpdate = Observable.FromEvent(
                 h => EditorApplication.update += new EditorApplication.CallbackFunction(h),
                 h => EditorApplication.update -= new EditorApplication.CallbackFunction(h)
             );

            _isAsyncOperationInProgressProperty
            .DistinctUntilChanged()
            .Select(active => active
             ? editorUpdate.ThrottleFirst(TimeSpan.FromMilliseconds(100))
             : Observable.Empty<Unit>())
             .Switch()
            .Subscribe(_ => onEditorUpdate())
            .AddTo(_compositeDisposable);
        }

        public void OnAsyncOperationStarted()
        {
            _isAsyncOperationInProgressProperty.Value = true;
            Debug.Log("calculation started");
        }
        public void OnAsyncOperationEnded()
        {
            _isAsyncOperationInProgressProperty.Value = false;
            Debug.Log("calculation ended");
        }

        public void Dispose()
        {
            IsDisposed = true;

            _cancellationTokenSource.Cancel();
            _cancellationTokenSource.Dispose();

            if (_isAsyncOperationInProgressProperty.Value)
                DisposeAsync();
            else
                FinalDispose();
        }


        private async void DisposeAsync()
        {
            using var cts = new CancellationTokenSource(TimeSpan.FromSeconds(30));

            try
            {
                Debug.LogWarning("job calculations still not finished, waiting for complete...");
                await _isAsyncOperationInProgressProperty
                    .Where(x => x == false)
                    .FirstAsync(cts.Token);
            }
            catch (OperationCanceledException)
            {
                Debug.LogWarning("dispose timeout! Did you forget to set async flag to false?");
            }
            catch (Exception ex)
            {
                Debug.LogException(ex);
            }
            finally
            {
                FinalDispose();
                Debug.LogWarning("all disposables disposed");
            }
        }

        private void FinalDispose()
        {
            _compositeDisposable.Dispose();
            _isAsyncOperationInProgressProperty.Dispose();
        }
    }
}
