using System.Collections;
using System.Collections.Generic;
using Unity.Burst;
using Unity.Mathematics;

namespace ZE.MechBattle.Navigation
{
    // generated by Google AI
    public interface IEdgeDirectionLogic
    {
        IntTriangularPos GetStart(int trianglesPerEdge, NavigationHexPosition hex);
        IntTriangularPos EvenStep(IntTriangularPos pos);
        IntTriangularPos OddStep(IntTriangularPos pos);
    }

    [BurstCompile]
    public struct EdgeEnumerator<T> : IEnumerator<IntTriangularPos> where T : struct, IEdgeDirectionLogic
    {
        private T _logic;
        private int _limit;
        private int _step;
        private int _subStep;
        private IntTriangularPos _pos;

        public EdgeEnumerator(int trianglesPerEdge, NavigationHexPosition hex)
        {
            _logic = default; 
            _limit = trianglesPerEdge;
            _pos = _logic.GetStart(trianglesPerEdge, hex);
            UnityEngine.Debug.Log(_pos.ToStandartized());
            _step = 0;
            _subStep = 0;
        }

        public bool MoveNext()
        {
            if (_step == -1)
            {
                _step = 0;
                return true;
            }
            if (_step == 0)
            {
                _step++;
                _subStep = 0;
                return true;
            }

            if (_step < _limit)
            {
                switch (_subStep)
                {
                    case 0: 
                        _pos = _logic.EvenStep(_pos);
                        _subStep = 1;
                        return true;

                    case 1: 
                        _pos = _logic.OddStep(_pos);
                        _subStep = 0;
                        _step++;
                        return true;
                }
            }
            return false;
        }

        public IntTriangularPos Current => _pos;
        object IEnumerator.Current => Current;
        public EdgeEnumerator<T> GetEnumerator() => this;
        public void Dispose() { }
        public void Reset() { }
    }


    public struct TopEdgeLogic : IEdgeDirectionLogic
    {
        // Top left corner -> top right

        public IntTriangularPos GetStart(int trianglesPerEdge, NavigationHexPosition hex)
        {
            return hex.TriangularCenterPos + new int3(0, trianglesPerEdge,- trianglesPerEdge + 1);            
        }
        public IntTriangularPos EvenStep(IntTriangularPos pos) => TriangularMath.GetValleyNeighbour(pos, ValleyNeighbour.EdgeDownRight);
        public IntTriangularPos OddStep(IntTriangularPos pos) => TriangularMath.GetPeakNeighbour(pos, PeakNeighbour.EdgeUpRight);
    }

    public struct TopRightEdgeLogic : IEdgeDirectionLogic
    {
        // Top right corner -> right corner

        public IntTriangularPos GetStart(int trianglesPerEdge, NavigationHexPosition hex)
        {
            return hex.TriangularCenterPos + new int3(-trianglesPerEdge, trianglesPerEdge - 1, 0);
        }
        public IntTriangularPos OddStep(IntTriangularPos pos) => TriangularMath.GetValleyNeighbour(pos, ValleyNeighbour.EdgeDownRight);
        public IntTriangularPos EvenStep(IntTriangularPos pos) => TriangularMath.GetPeakNeighbour(pos, PeakNeighbour.EdgeDown);
    }

    public struct BottomRightEdgeLogic : IEdgeDirectionLogic
    {
        // right corner -> bottom right corner
        public IntTriangularPos GetStart(int trianglesPerEdge, NavigationHexPosition hex)
        {
            return hex.TriangularCenterPos + new int3(-trianglesPerEdge + 1, 0, trianglesPerEdge);
        }
        public IntTriangularPos OddStep(IntTriangularPos pos) => TriangularMath.GetPeakNeighbour(pos, PeakNeighbour.EdgeDown);
        public IntTriangularPos EvenStep(IntTriangularPos pos) => TriangularMath.GetValleyNeighbour(pos, ValleyNeighbour.EdgeDownLeft);
    }

    public struct BottomEdgeLogic : IEdgeDirectionLogic
    {
        // bottom left corner -> bottom right corner
        public IntTriangularPos GetStart(int trianglesPerEdge, NavigationHexPosition hex)
        {
            return hex.TriangularCenterPos + new int3(trianglesPerEdge - 1, -trianglesPerEdge, 0);
        }
        public IntTriangularPos EvenStep(IntTriangularPos pos) => TriangularMath.GetPeakNeighbour(pos, PeakNeighbour.EdgeUpRight);
        public IntTriangularPos OddStep(IntTriangularPos pos) => TriangularMath.GetValleyNeighbour(pos, ValleyNeighbour.EdgeDownRight);
    }

    public struct BottomLeftEdgeLogic : IEdgeDirectionLogic
    {
        // left corner -> bottom left corner
        public IntTriangularPos GetStart(int trianglesPerEdge, NavigationHexPosition hex)
        {
            return hex.TriangularCenterPos + new int3(trianglesPerEdge, 0, -trianglesPerEdge + 1);
        }
        public IntTriangularPos OddStep(IntTriangularPos pos) => TriangularMath.GetPeakNeighbour(pos, PeakNeighbour.EdgeDown);
        public IntTriangularPos EvenStep(IntTriangularPos pos) => TriangularMath.GetValleyNeighbour(pos, ValleyNeighbour.EdgeDownRight);
    }

    public struct TopLeftEdgeLogic : IEdgeDirectionLogic
    {
        // left corner -> top left corner
        public IntTriangularPos GetStart(int trianglesPerEdge, NavigationHexPosition hex)
        {
            return hex.TriangularCenterPos + new int3(trianglesPerEdge-1, 0, -trianglesPerEdge);
        }
        public IntTriangularPos EvenStep(IntTriangularPos pos) => TriangularMath.GetPeakNeighbour(pos, PeakNeighbour.EdgeUpRight);
        public IntTriangularPos OddStep(IntTriangularPos pos) => TriangularMath.GetValleyNeighbour(pos, ValleyNeighbour.EdgeUp);
    }
}
