using UnityEngine;
using Unity.Burst;
using Unity.Mathematics;
using System.Runtime.CompilerServices;

namespace ZE.MechBattle.Navigation
{
    public static class HexMath
    {
        [BurstCompile]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static int2 GetNeighbourCoord(int2 hexCoord, int edgeIndex)
        {
            var edge = (HexEdge)edgeIndex;
            return hexCoord + edge.ToHexOffsetVector();
        }

        // Generated by Google AI
        [BurstCompile]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static bool AreNeighbours(int2 a, int2 b)
        {
            uint2 d = (uint2)((b - a) + 1);

            if (d.x > 2 || d.y > 2) return false;

            int index = (int)(d.x * 3 + d.y);
            const int MASK = 0b_11101110;
            return (MASK & (1 << index)) != 0;
        }

        [BurstCompile]
        public static HexEdge HexOffsetVectorToEdge(this int2 vector)
        {            
            //6=(-1,1)=TopLeft(5)     7=(0,1)=Top(0)
            //3=(-1,0)=BottomLeft(4)  4=(0,0)=X           5=(1,0)=TopRight(1)
            //0=(-1,-1)=X             1=(0,-1)=Bottom(3)  2=(1,-1)=BottomRight(2)

            var index = (vector.x + 1) + (vector.y+1)*3;
            const long HEX_OFFSET_DATA_REVERSED_MASK = 0x_0_5_1_0_4_2_3_0;
            var encodedValue = (HEX_OFFSET_DATA_REVERSED_MASK >> (index * 4)) & 0xF;
            return (HexEdge)encodedValue;
        }

        // generated by Google AI
        [BurstCompile]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static int GetDelta(HexEdge a, HexEdge b)
        {
            int diff = math.abs((int)a - (int)b);
            // indices:  0 1 2 3 4 5
            // values: 0 1 2 2 2 1  (4 bit per each)
            // ex. for a = Top: Top -> 0, TopRight,TopLeft -> 1, other -> 2
            // 
            const int deltaTable = 0x122210;
            return (deltaTable >> (diff * 4)) & 0xF;
        }

        // chatGPT generated
        [BurstCompile]
        public static int CalculateHexPosDistance(int2 hexPosA, int2 hexPosB)
        {
            int x1 = hexPosA.x;
            int z1 = hexPosA.y;
            int y1 = -x1 - z1;

            int x2 = hexPosB.x;
            int z2 = hexPosB.y;
            int y2 = -x2 - z2;

            return math.max(
                math.abs(x1 - x2),
                math.max(
                    math.abs(y1 - y2),
                    math.abs(z1 - z2)
                )
            );
        }

        [BurstCompile]
        public static float CalculateHexPosDistance(float2 hexPosA, float2 hexPosB)
        {
            var x1 = hexPosA.x;
            var z1 = hexPosA.y;
            var y1 = -x1 - z1;

            var x2 = hexPosB.x;
            var z2 = hexPosB.y;
            var y2 = -x2 - z2;

            return math.max(
                math.abs(x1 - x2),
                math.max(
                    math.abs(y1 - y2),
                    math.abs(z1 - z2)
                )
            );
        }

        [BurstCompile]
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static float CalculateDistance(HexEdgeKey A, HexEdgeKey B) =>
            CalculateHexPosDistance(A.EdgeCenterHexCoord, B.EdgeCenterHexCoord);

        //chatgpt generated
        [BurstCompile]
        public static int2 DefineHex(float2 worldPos, float hexEdge)
        {
            var q = (2f / 3f * worldPos.x) / hexEdge;
            var r = (-1f / 3f * worldPos.x + NavigationConstants.SQRT_THREE_D_3 * worldPos.y) / hexEdge;

            return AxialRound(q, r);
        }

        [BurstCompile]
        public static int2 DefineHex(IntTriangularPos tripos, float triangleHeight, float hexEdge) =>
            TriangularMath.TriangularToHex(tripos, triangleHeight, hexEdge);

        [BurstCompile]
        public static float2 WorldToHex(float2 worldPos, float hexEdge)
        {
            var q = (2f / 3f * worldPos.x) / hexEdge;
            var r = (-1f / 3f * worldPos.x + NavigationConstants.SQRT_THREE_D_3 * worldPos.y) / hexEdge;

            return new(q, r);
        }

        //chatgpt generated
        [BurstCompile]
        public static float2 HexToWorld(int2 pos, float hexEdge)
        {
            var x = hexEdge * (3f / 2f * pos.x);
            var y = hexEdge * (NavigationConstants.SQRT_OF_THREE * (pos.y + pos.x / 2f));
            return new float2(x, y);
        }

        [BurstCompile]
        public static float2 HexToWorld(float2 pos, float hexEdge)
        {
            var x = hexEdge * (3f / 2f * pos.x);
            var y = hexEdge * (NavigationConstants.SQRT_OF_THREE * (pos.y + pos.x / 2f));
            return new float2(x, y);
        }

        //chatgpt generated
        [BurstCompile]
        private static int2 AxialRound(float q, float r)
        {
            var x = q;
            var z = r;
            var y = -x - z;

            var rx = (int)math.round(x);
            var ry = (int)math.round(y);
            var rz = (int)math.round(z);

            var dx = math.abs(rx - x);
            var dy = math.abs(ry - y);
            var dz = math.abs(rz - z);

            if (dx > dy && dx > dz)
                rx = -ry - rz;
            else if (dy > dz)
                ry = -rx - rz;
            else
                rz = -rx - ry;

            return new int2(rx, rz);
        }
    }
}
