using UnityEngine;
using Unity.Mathematics;
using Unity.Burst;
using System.Runtime.CompilerServices;

namespace ZE.MechBattle.Navigation
{
    public static class TriangularMath
    {
        // note: triangle grid is XZ plane, but with 3 orths
        public static readonly float3 DirY = new float3(0,0f,1f);
        public static readonly float3 DirZ = math.normalize( math.mul(quaternion.AxisAngle(math.up(), math.radians(120f)), math.forward()));
        public static readonly float3 DirX = math.normalize( math.mul(quaternion.AxisAngle(math.down(), math.radians(120f)), math.forward()));

        private const float FACTOR = 2f / 3f;

        [BurstCompile]
        public static IntTriangularPos DoOffsetAlongEdge(IntTriangularPos start, HexEdge edge, int offset)
        {
            var half = offset / 2;
            var otherHalf = offset - half;
            var peakDirection = edge.ToAlongsidePeakDirection().ToTriangularOffsetVector();
            var valleyDirection = edge.ToAlongsideValleyDirection().ToTriangularOffsetVector();

            return start + (start.IsPeak 
                ? (half * peakDirection + otherHalf * valleyDirection)
                : (half * valleyDirection + otherHalf * peakDirection));
        }

        [BurstCompile]
        public static IntTriangularPos GetPeakNeighbour(IntTriangularPos pos, PeakNeighbour peakNeighbour, int offset = 1) => 
            pos + peakNeighbour.ToTriangularOffsetVector();

        [BurstCompile]
        public static IntTriangularPos GetPeakNeighbour(IntTriangularPos pos, int peakNeighbour) => 
            GetPeakNeighbour(pos, (PeakNeighbour)peakNeighbour);

        // generated by Google AI based on GetPeakNeighbour()
        [BurstCompile]
        public static PeakNeighbour DefinePeakNeighbour(IntTriangularPos origin, IntTriangularPos target)
        {
            int dDL = target.DownLeft - origin.DownLeft;
            int dUp = target.Up - origin.Up;
            int dDR = target.DownRight - origin.DownRight;

            return (dDL, dUp, dDR) switch
            {
                (-1, 1, 0) => PeakNeighbour.VertexUpRight,
                (0, 1, 1) => PeakNeighbour.EdgeUpRight,
                (-1, 0, 1) => PeakNeighbour.VertexRight,
                (0, 0, 2) => PeakNeighbour.VertexDownRightValley,
                (0, -1, 1) => PeakNeighbour.VertexDownRightPeak,
                (1, 0, 1) => PeakNeighbour.EdgeDown,
                (1, -1, 0) => PeakNeighbour.VertexDownLeftPeak,
                (2, 0, 0) => PeakNeighbour.VertexDownLeftValley,
                (1, 0, -1) => PeakNeighbour.VertexLeft,
                (1, 1, 0) => PeakNeighbour.EdgeUpLeft,
                (0, 1, -1) => PeakNeighbour.VertexUpLeft,
                _ => PeakNeighbour.VertexUp //
            };
        }

        [BurstCompile]
        public static IntTriangularPos GetValleyNeighbour(IntTriangularPos pos, ValleyNeighbour valleyNeighbour) => 
            pos + valleyNeighbour.ToTriangularOffsetVector();

        [BurstCompile]
        public static IntTriangularPos GetValleyNeighbour(IntTriangularPos pos, int valleyNeighbour) => GetValleyNeighbour(pos, (ValleyNeighbour)valleyNeighbour);

        // generated by Google AI based on GetValleyNeighbour()
        [BurstCompile]
        public static ValleyNeighbour DefineValleyNeighbour(IntTriangularPos origin, IntTriangularPos target)
        {
            int dDL = target.DownLeft - origin.DownLeft;
            int dUp = target.Up - origin.Up;
            int dDR = target.DownRight - origin.DownRight;

            return (dDL, dUp, dDR) switch
            {
                (-1, 1, 0) => ValleyNeighbour.VertexUpRightValley,
                (-2, 0, 0) => ValleyNeighbour.VertexUpRightPeak,
                (-1, 0, 1) => ValleyNeighbour.VertexRight,
                (-1, -1, 0) => ValleyNeighbour.EdgeDownRight,
                (0, -1, 1) => ValleyNeighbour.VertexDownRight,
                (0, -2, 0) => ValleyNeighbour.VertexDown,
                (1, -1, 0) => ValleyNeighbour.VertexDownLeft,
                (0, -1, -1) => ValleyNeighbour.EdgeDownLeft,
                (1, 0, -1) => ValleyNeighbour.VertexLeft,
                (0, 0, -2) => ValleyNeighbour.VertexUpLeftPeak,
                (0, 1, -1) => ValleyNeighbour.VertexUpLeftValley,
                _ => ValleyNeighbour.EdgeUp 
            };
        }


        [BurstCompile]
        public static IntTriangularPos GetNeighbourByDirection(IntTriangularPos pos, int direction) =>
            pos.IsPeak 
            ? GetPeakNeighbour(pos, direction)
            : GetValleyNeighbour(pos,direction);

        [BurstCompile]
        public static byte GetHexEdgeExitVector(HexEdge edge, bool isPeak) => edge switch
        {
            HexEdge.TopRight => isPeak ? (byte)PeakNeighbour.EdgeUpRight : (byte)ValleyNeighbour.VertexUpRightPeak,
            HexEdge.BottomRight => isPeak ? (byte)PeakNeighbour.VertexDownRightValley : (byte)ValleyNeighbour.EdgeDownRight,
            HexEdge.BottomLeft => isPeak ? (byte)PeakNeighbour.VertexDownLeftValley : (byte)ValleyNeighbour.EdgeDownLeft,
            HexEdge.TopLeft => isPeak ? (byte)PeakNeighbour.EdgeUpLeft : (byte)ValleyNeighbour.VertexUpLeftPeak,
            HexEdge.Bottom => isPeak ? (byte)PeakNeighbour.EdgeDown : (byte)ValleyNeighbour.VertexDown,
            _ => isPeak ? (byte)PeakNeighbour.VertexUp : (byte)ValleyNeighbour.EdgeUp,
        };

        /// <summary>
        /// Converts encoded flow map direction into normalized vector. For mass operations better use vectors caching!
        /// </summary>
        [BurstCompile]
        public static float3 TriangularDirectionToWorld(byte direction, bool usePeakNeighbours)
        {
            IntTriangularPos nextPos;
            if (usePeakNeighbours)
                nextPos = TriangularMath.GetPeakNeighbour(default, (PeakNeighbour)direction);
            else
                nextPos = TriangularMath.GetValleyNeighbour(default, (ValleyNeighbour)direction);

            return math.normalize(nextPos.DownLeft * TriangularMath.DirX + nextPos.Up * TriangularMath.DirY + nextPos.DownRight * TriangularMath.DirZ);
        }


        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static int GetTrianglesCountInHex(int hexRadius) => hexRadius * hexRadius * 6;


        /// <summary>
        /// Returns both peak and valley triangles count of hex edge
        /// </summary>
        /*TopRight example:
         * vavA
         *  vaVA
         *   vaVA
         *  vava
         * vava
         */
        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static int GetTwoRowEdgeTrianglesCount(int hexRadius) => 2 * hexRadius - 1;



        // generated by Google AI
        [BurstCompile]
        public static float3 TriangularToWorld(float3 tri, float triangleHeight)
        {
            var v = new float3(tri.x + 0.5f, tri.y + 0.5f, tri.z + 0.5f) * triangleHeight;
            var worldPos = FACTOR * (v.x * DirX + v.y * DirY + v.z * DirZ);

            return worldPos;
        }

        // generated by Google AI
        [BurstCompile]
        public static float3 TriangularToWorld(int3 tri, float triangleHeight)
        {
            // 1. Find the "barycentric center" in the index space.
            // If the sum (nx+ny+nz) is 1, it's a Valley. If 2, it's a Peak (or vice versa, depending on the offset).
            // To find the center of the triangle, we add a 0.5 offset to each line index
            // to land exactly halfway between line n and n+1.
            var v = new float3(tri.x + 0.5f, tri.y + 0.5f, tri.z + 0.5f) * triangleHeight;

            // 2. Transform from the 3-axis projection space back to World Space (X, Z).
            // Since your normals lie in the XZ plane (with Y as Unity's Up axis),
            // the world coordinates are derived from the weighted sum of projections.

            // The 2/3 factor arises from the properties of a triaxial grid (projection onto 3 axes at 120°).

            var worldPos = FACTOR * (v.x * DirX + v.y * DirY + v.z * DirZ);

            return worldPos;
        }

        
        [BurstCompile]
        public static IntTriangularPos WorldToTrianglePos(float3 pos, float triangleHeight) => WorldToTrianglePosInvertedHeight(pos, 1.0f / triangleHeight);

        // Optimized by Google AI
        [BurstCompile]
        public static IntTriangularPos WorldToTrianglePosInvertedHeight(float3 worldPos, float invertedTriangleHeight) 
        {
            float3 projections = new float3(
                math.dot(worldPos, DirX),
                math.dot(worldPos, DirY),
                math.dot(worldPos, DirZ)
            );

            float3 v = projections * invertedTriangleHeight;
            float3 f = math.floor(v);
            int3 n0 = (int3)f;
            int3 n1 = n0 + 1;

            var result = (n1.x + n1.y + n0.z == 0)
                ? new IntTriangularPos(n1.x, n1.y, n1.z)
                : new IntTriangularPos(n0.x, n0.y, n0.z);

            return result.IsPointCoordinate() ? new IntTriangularPos(result.X, result.Y + 1, result.Z) : result;
        }

        // generated by Google AI
        [BurstCompile]
        public static float3 WorldToTriangular(float3 pos, double triangleHeight)
        {
            var p = (double3)pos;

            var vX = math.dot(p, (double3)DirX) / triangleHeight;
            var vY = math.dot(p, (double3)DirY) / triangleHeight;
            var vZ = math.dot(p, (double3)DirZ) / triangleHeight;

            return new float3((float)vX, (float)vY, (float)vZ);
        }

        [BurstCompile]
        public static int2 TriangularToHex(IntTriangularPos pos, float triangleHeight, float hexEdgeLength)
        {
            // there is no correct method to convert directly yet
            var world = TriangularToWorld(pos, triangleHeight);
            return HexMath.DefineHex(world.xz, hexEdgeLength);
        }


        // explanation: https://www.boristhebrave.com/2021/05/27/some-triangle-grid-extensions/
        [BurstCompile]
        public static int CalculateDistance(IntTriangularPos start, IntTriangularPos end) => ( math.abs(start.X - end.X) + math.abs(start.Y - end.Y) + math.abs(start.Z - end.Z)) / 2;

        
        [BurstCompile]
        public static HexSector DefineSector(IntTriangularPos pos, float hexEdgeLength, int hexRadius, float triangleHeight)
        {
            var hexCoord = TriangularMath.TriangularToHex(pos, triangleHeight, hexEdgeLength);
            var hexPos = new NavigationHexPosition(hexCoord, hexEdgeLength, hexRadius);

            var hexCenter = hexPos.TriangularCenterPos;
            var isPeak = pos.IsPeak;
            var peakMask = new bool3(isPeak, isPeak, isPeak);

            /*  original logic
            var xDivision = pos.X == hexCenter.X ? (isPeak ? 1 : -1) : (pos.X > hexCenter.X ? 1 : -1);
            var yDivision = pos.Y == hexCenter.Y ? (isPeak ? 1 : -1) : (pos.Y > hexCenter.Y ? 1 : -1);
            var zDivision = pos.Z == hexCenter.Z ? (isPeak ? 1: -1) : (pos.Z > hexCenter.Z ? 1 : -1);

            if (xDivision == 1)
            {
                if (yDivision == 1)
                {
                    return HexSector.TopLeft;
                }
                else
                {
                    return zDivision == 1 ? HexSector.Bottom : HexSector.BottomLeft;
                }
            }
            else
            {
                if (yDivision == 1)
                    return zDivision == 1 ? HexSector.TopRight : HexSector.Top;
                else
                    return HexSector.BottomRight;
            }
            */

            // burst logic optimized by Google AI
            var p = pos.ToInt3();
            var c = hexCenter.ToInt3();
            bool3 isGreater = p > c;
            bool3 isEqual = p == c;

            bool3 mask = (isEqual & isPeak) | (!isEqual & isGreater);
            int3 maskInt = math.select(new int3(0), new int3(4, 2, 1), mask);
            int index = maskInt.x + maskInt.y + maskInt.z;

            //return index switch
            //{
            //    0b110 => HexSector.TopLeft,
            //    0b111 => HexSector.TopLeft,
            //    0b101 => HexSector.Bottom,      // X=1, Y=0, Z=1
            //    0b100 => HexSector.BottomLeft,  // X=1, Y=0, Z=0
            //    0b011 => HexSector.TopRight,    // X=0, Y=1, Z=1
            //    0b010 => HexSector.Top,         // X=0, Y=1, Z=0
            //    0b000 => HexSector.BottomRight, // X=0, Y=0, Z=0
            //    _ => HexSector.BottomRight
            //};
            const ulong packedLut = 0x55341022;

            // shift (index * 4) bit and get last 4 bits
            int sectorValue = (int)((packedLut >> (index * 4)) & 0xF);

            return (HexSector)sectorValue;
        }

        [BurstCompile]
        public static float GetPeakTransitionCost(PeakNeighbour neighbour)
        {
            switch (neighbour)
            {
                case PeakNeighbour.VertexUp:
                case PeakNeighbour.VertexDownRightValley:
                case PeakNeighbour.VertexDownLeftValley:
                    return NavigationConstants.VERTEX_PASS_COST;
                case PeakNeighbour.EdgeDown:
                case PeakNeighbour.EdgeUpLeft:
                case PeakNeighbour.EdgeUpRight:
                    return NavigationConstants.EDGE_PASS_COST;
                default:
                    return NavigationConstants.LONG_VERTEX_PASS_COST;
            }
        }

        [BurstCompile]
        public static float GetValleyTransitionCost(ValleyNeighbour neighbour)
        {
            switch (neighbour)
            {
                case ValleyNeighbour.VertexUpRightPeak:
                case ValleyNeighbour.VertexDown:
                case ValleyNeighbour.VertexUpLeftPeak:
                    return NavigationConstants.VERTEX_PASS_COST;
                case ValleyNeighbour.EdgeUp:
                case ValleyNeighbour.EdgeDownLeft:
                case ValleyNeighbour.EdgeDownRight:
                    return NavigationConstants.EDGE_PASS_COST;
                default:
                    return NavigationConstants.LONG_VERTEX_PASS_COST;
            }
        }

        [BurstCompile]
        public static float GetTransitionCost(int neighbourIndex, bool isPeak) => isPeak ? GetPeakTransitionCost((PeakNeighbour)neighbourIndex) : GetValleyTransitionCost((ValleyNeighbour)neighbourIndex);

        [BurstCompile]
        public static int GetDirectionsDelta(int targetDir, int currentDir)
        {
            const int HALF_DIR = NavigationConstants.TRIANGLE_DIRECTIONS_COUNT / 2;
            var delta = math.abs(targetDir - currentDir);
            if (delta > HALF_DIR) delta = NavigationConstants.TRIANGLE_DIRECTIONS_COUNT - delta;
            return delta;
        }

        [MethodImpl(MethodImplOptions.AggressiveInlining)]
        public static float GetTriangleHeight(float triangleEdge) => triangleEdge * NavigationConstants.SQRT_OF_THREE_HALVED;

        [BurstCompile]
        public static TransitionMeasurePoints GetTransitionMeasurePoints(IntTriangularPos start, IntTriangularPos end)
        {
            if (start.IsPeak)
                return TriangularMath.DefinePeakNeighbour(start, end).GetTransitionMeasurePoints();
            else
                return TriangularMath.DefineValleyNeighbour(start, end).GetTransitionMeasurePoints();
        }

        [BurstCompile]
        public static int GetJumpNeighbourCheckIndex(bool isPeak, int jumpNeighbourIndex) =>
         isPeak
         ? ((PeakNeighbour)jumpNeighbourIndex).GetJumpNeighbourCheckIndex()
         : ((ValleyNeighbour)jumpNeighbourIndex).GetJumpNeighbourCheckIndex();
    }
}
